// Auto-generated - do not edit manually
export type { IconProps, IconNode, FoamIcon } from './types';
export { createFoamicon } from './createFoamicon';
export { Icon } from './Icon';

export { AlertDuotone } from './icons/AlertDuotone';
export { AlertFill } from './icons/AlertFill';
export { Alert } from './icons/Alert';
export { ArchiveArrowUpDuotone } from './icons/ArchiveArrowUpDuotone';
export { ArchiveArrowUpFill } from './icons/ArchiveArrowUpFill';
export { ArchiveArrowUp } from './icons/ArchiveArrowUp';
export { ArchiveDuotone } from './icons/ArchiveDuotone';
export { ArchiveFill } from './icons/ArchiveFill';
export { Archive } from './icons/Archive';
export { ArrowDown01Duotone } from './icons/ArrowDown01Duotone';
export { ArrowDown01Fill } from './icons/ArrowDown01Fill';
export { ArrowDown01 } from './icons/ArrowDown01';
export { ArrowDown10Duotone } from './icons/ArrowDown10Duotone';
export { ArrowDown10Fill } from './icons/ArrowDown10Fill';
export { ArrowDown10 } from './icons/ArrowDown10';
export { ArrowDownIGDuotone } from './icons/ArrowDownIGDuotone';
export { ArrowDownIGFill } from './icons/ArrowDownIGFill';
export { ArrowDownIG } from './icons/ArrowDownIG';
export { ArrowDownSCDuotone } from './icons/ArrowDownSCDuotone';
export { ArrowDownSCFill } from './icons/ArrowDownSCFill';
export { ArrowDownSC } from './icons/ArrowDownSC';
export { ArrowDownTTDuotone } from './icons/ArrowDownTTDuotone';
export { ArrowDownTTFill } from './icons/ArrowDownTTFill';
export { ArrowDownTT } from './icons/ArrowDownTT';
export { ArrowDownYTDuotone } from './icons/ArrowDownYTDuotone';
export { ArrowDownYTFill } from './icons/ArrowDownYTFill';
export { ArrowDownYT } from './icons/ArrowDownYT';
export { ArrowDownDuotone } from './icons/ArrowDownDuotone';
export { ArrowDownFill } from './icons/ArrowDownFill';
export { ArrowDownNarrowWideDuotone } from './icons/ArrowDownNarrowWideDuotone';
export { ArrowDownNarrowWideFill } from './icons/ArrowDownNarrowWideFill';
export { ArrowDownNarrowWide } from './icons/ArrowDownNarrowWide';
export { ArrowDownUpDuotone } from './icons/ArrowDownUpDuotone';
export { ArrowDownUpFill } from './icons/ArrowDownUpFill';
export { ArrowDownUp } from './icons/ArrowDownUp';
export { ArrowDownWideNarrowDuotone } from './icons/ArrowDownWideNarrowDuotone';
export { ArrowDownWideNarrowFill } from './icons/ArrowDownWideNarrowFill';
export { ArrowDownWideNarrow } from './icons/ArrowDownWideNarrow';
export { ArrowDown } from './icons/ArrowDown';
export { ArrowLeftDuotone } from './icons/ArrowLeftDuotone';
export { ArrowLeftFill } from './icons/ArrowLeftFill';
export { ArrowLeft } from './icons/ArrowLeft';
export { ArrowRightDuotone } from './icons/ArrowRightDuotone';
export { ArrowRightFill } from './icons/ArrowRightFill';
export { ArrowRightToLineDuotone } from './icons/ArrowRightToLineDuotone';
export { ArrowRightToLineFill } from './icons/ArrowRightToLineFill';
export { ArrowRightToLine } from './icons/ArrowRightToLine';
export { ArrowRight } from './icons/ArrowRight';
export { ArrowUpIGDuotone } from './icons/ArrowUpIGDuotone';
export { ArrowUpIGFill } from './icons/ArrowUpIGFill';
export { ArrowUpIG } from './icons/ArrowUpIG';
export { ArrowUpSCDuotone } from './icons/ArrowUpSCDuotone';
export { ArrowUpSCFill } from './icons/ArrowUpSCFill';
export { ArrowUpSC } from './icons/ArrowUpSC';
export { ArrowUpTTDuotone } from './icons/ArrowUpTTDuotone';
export { ArrowUpTTFill } from './icons/ArrowUpTTFill';
export { ArrowUpTT } from './icons/ArrowUpTT';
export { ArrowUpYTDuotone } from './icons/ArrowUpYTDuotone';
export { ArrowUpYTFill } from './icons/ArrowUpYTFill';
export { ArrowUpYT } from './icons/ArrowUpYT';
export { ArrowUpAZDuotone } from './icons/ArrowUpAZDuotone';
export { ArrowUpAZFill } from './icons/ArrowUpAZFill';
export { ArrowUpAZ } from './icons/ArrowUpAZ';
export { ArrowUpDuotone } from './icons/ArrowUpDuotone';
export { ArrowUpFill } from './icons/ArrowUpFill';
export { ArrowUpNarrowWideDuotone } from './icons/ArrowUpNarrowWideDuotone';
export { ArrowUpNarrowWideFill } from './icons/ArrowUpNarrowWideFill';
export { ArrowUpNarrowWide } from './icons/ArrowUpNarrowWide';
export { ArrowUpWideNarrowDuotone } from './icons/ArrowUpWideNarrowDuotone';
export { ArrowUpWideNarrowFill } from './icons/ArrowUpWideNarrowFill';
export { ArrowUpWideNarrow } from './icons/ArrowUpWideNarrow';
export { ArrowUpZADuotone } from './icons/ArrowUpZADuotone';
export { ArrowUpZAFill } from './icons/ArrowUpZAFill';
export { ArrowUpZA } from './icons/ArrowUpZA';
export { ArrowUp } from './icons/ArrowUp';
export { BanDuotone } from './icons/BanDuotone';
export { BanFill } from './icons/BanFill';
export { Ban } from './icons/Ban';
export { BellDuotone } from './icons/BellDuotone';
export { BellFill } from './icons/BellFill';
export { Bell } from './icons/Bell';
export { BoldDuotone } from './icons/BoldDuotone';
export { BoldFill } from './icons/BoldFill';
export { Bold } from './icons/Bold';
export { BookmarkDuotone } from './icons/BookmarkDuotone';
export { BookmarkFill } from './icons/BookmarkFill';
export { Bookmark } from './icons/Bookmark';
export { CalendarDuotone } from './icons/CalendarDuotone';
export { CalendarFill } from './icons/CalendarFill';
export { Calendar } from './icons/Calendar';
export { ChartColumnSquareDuotone } from './icons/ChartColumnSquareDuotone';
export { ChartColumnSquareFill } from './icons/ChartColumnSquareFill';
export { ChartColumnSquare } from './icons/ChartColumnSquare';
export { CheckboxDuotone } from './icons/CheckboxDuotone';
export { CheckboxFill } from './icons/CheckboxFill';
export { Checkbox } from './icons/Checkbox';
export { CheckmarkDuotone } from './icons/CheckmarkDuotone';
export { CheckmarkFill } from './icons/CheckmarkFill';
export { Checkmark } from './icons/Checkmark';
export { ChevronDownDuotone } from './icons/ChevronDownDuotone';
export { ChevronDownFill } from './icons/ChevronDownFill';
export { ChevronDown } from './icons/ChevronDown';
export { ChevronLeftDuotone } from './icons/ChevronLeftDuotone';
export { ChevronLeftFill } from './icons/ChevronLeftFill';
export { ChevronLeft } from './icons/ChevronLeft';
export { ChevronRightDuotone } from './icons/ChevronRightDuotone';
export { ChevronRightFill } from './icons/ChevronRightFill';
export { ChevronRight } from './icons/ChevronRight';
export { ChevronUpDuotone } from './icons/ChevronUpDuotone';
export { ChevronUpFill } from './icons/ChevronUpFill';
export { ChevronUp } from './icons/ChevronUp';
export { CircleAlertDuotone } from './icons/CircleAlertDuotone';
export { CircleAlertFill } from './icons/CircleAlertFill';
export { CircleAlert } from './icons/CircleAlert';
export { CircleDollarSignDuotone } from './icons/CircleDollarSignDuotone';
export { CircleDollarSignFill } from './icons/CircleDollarSignFill';
export { CircleDollarSign } from './icons/CircleDollarSign';
export { CircleQuestionMarkDuotone } from './icons/CircleQuestionMarkDuotone';
export { CircleQuestionMarkFill } from './icons/CircleQuestionMarkFill';
export { CircleQuestionMark } from './icons/CircleQuestionMark';
export { CircleXDuotone } from './icons/CircleXDuotone';
export { CircleXFill } from './icons/CircleXFill';
export { CircleX } from './icons/CircleX';
export { ClockArrowDown1 } from './icons/ClockArrowDown1';
export { ClockArrowDownDuotone } from './icons/ClockArrowDownDuotone';
export { ClockArrowDownFill } from './icons/ClockArrowDownFill';
export { ClockArrowDown } from './icons/ClockArrowDown';
export { ClockArrowUp1 } from './icons/ClockArrowUp1';
export { ClockArrowUpDuotone } from './icons/ClockArrowUpDuotone';
export { ClockArrowUpFill } from './icons/ClockArrowUpFill';
export { ClockArrowUp } from './icons/ClockArrowUp';
export { ClockDuotone } from './icons/ClockDuotone';
export { ClockFill } from './icons/ClockFill';
export { Clock } from './icons/Clock';
export { CogDuotone } from './icons/CogDuotone';
export { CogFill } from './icons/CogFill';
export { Cog } from './icons/Cog';
export { Columns3Duotone } from './icons/Columns3Duotone';
export { Columns3Fill } from './icons/Columns3Fill';
export { Columns3 } from './icons/Columns3';
export { CommandDuotone } from './icons/CommandDuotone';
export { CommandFill } from './icons/CommandFill';
export { Command } from './icons/Command';
export { ContentPlusDuotone } from './icons/ContentPlusDuotone';
export { ContentPlusFill } from './icons/ContentPlusFill';
export { ContentPlus } from './icons/ContentPlus';
export { CopyDuotone } from './icons/CopyDuotone';
export { CopyFill } from './icons/CopyFill';
export { Copy } from './icons/Copy';
export { DownloadDuotone } from './icons/DownloadDuotone';
export { DownloadFill } from './icons/DownloadFill';
export { Download } from './icons/Download';
export { EclipseDuotone } from './icons/EclipseDuotone';
export { EclipseFill } from './icons/EclipseFill';
export { Eclipse } from './icons/Eclipse';
export { ExternalLinkDuotone } from './icons/ExternalLinkDuotone';
export { ExternalLinkFill } from './icons/ExternalLinkFill';
export { ExternalLink } from './icons/ExternalLink';
export { EyeDuotone } from './icons/EyeDuotone';
export { EyeFill } from './icons/EyeFill';
export { EyeOffDuotone } from './icons/EyeOffDuotone';
export { EyeOffFill } from './icons/EyeOffFill';
export { EyeOff } from './icons/EyeOff';
export { Eye } from './icons/Eye';
export { FlameDuotone } from './icons/FlameDuotone';
export { FlameFill } from './icons/FlameFill';
export { Flame } from './icons/Flame';
export { FrownDuotone } from './icons/FrownDuotone';
export { FrownFill } from './icons/FrownFill';
export { Frown } from './icons/Frown';
export { FullscreenDuotone } from './icons/FullscreenDuotone';
export { FullscreenFill } from './icons/FullscreenFill';
export { Fullscreen } from './icons/Fullscreen';
export { GlobeDuotone } from './icons/GlobeDuotone';
export { GlobeFill } from './icons/GlobeFill';
export { Globe } from './icons/Globe';
export { Grid1x2Duotone } from './icons/Grid1x2Duotone';
export { Grid1x2Fill } from './icons/Grid1x2Fill';
export { Grid1x2 } from './icons/Grid1x2';
export { Grid2x2Duotone } from './icons/Grid2x2Duotone';
export { Grid2x2Fill } from './icons/Grid2x2Fill';
export { Grid2x2 } from './icons/Grid2x2';
export { HistoryDuotone } from './icons/HistoryDuotone';
export { HistoryFill } from './icons/HistoryFill';
export { History } from './icons/History';
export { HotspotDuotone } from './icons/HotspotDuotone';
export { HotspotFill } from './icons/HotspotFill';
export { Hotspot } from './icons/Hotspot';
export { HouseDuotone } from './icons/HouseDuotone';
export { HouseFill } from './icons/HouseFill';
export { House } from './icons/House';
export { ImageDuotone } from './icons/ImageDuotone';
export { ImageFill } from './icons/ImageFill';
export { Image } from './icons/Image';
export { ImagesDuotone } from './icons/ImagesDuotone';
export { ImagesFill } from './icons/ImagesFill';
export { Images } from './icons/Images';
export { InboxDuotone } from './icons/InboxDuotone';
export { InboxFill } from './icons/InboxFill';
export { Inbox } from './icons/Inbox';
export { InfoDuotone } from './icons/InfoDuotone';
export { InfoFill } from './icons/InfoFill';
export { Info } from './icons/Info';
export { ItalicDuotone } from './icons/ItalicDuotone';
export { ItalicFill } from './icons/ItalicFill';
export { Italic } from './icons/Italic';
export { LinkDuotone } from './icons/LinkDuotone';
export { LinkFill } from './icons/LinkFill';
export { Link } from './icons/Link';
export { ListDuotone } from './icons/ListDuotone';
export { ListFill } from './icons/ListFill';
export { ListFilterDuotone } from './icons/ListFilterDuotone';
export { ListFilterFill } from './icons/ListFilterFill';
export { ListFilter } from './icons/ListFilter';
export { ListIndentDecreaseDuotone } from './icons/ListIndentDecreaseDuotone';
export { ListIndentDecreaseFill } from './icons/ListIndentDecreaseFill';
export { ListIndentDecrease } from './icons/ListIndentDecrease';
export { ListIndentIncreaseDuotone } from './icons/ListIndentIncreaseDuotone';
export { ListIndentIncreaseFill } from './icons/ListIndentIncreaseFill';
export { ListIndentIncrease } from './icons/ListIndentIncrease';
export { ListOrderedDuotone } from './icons/ListOrderedDuotone';
export { ListOrderedFill } from './icons/ListOrderedFill';
export { ListOrdered } from './icons/ListOrdered';
export { List } from './icons/List';
export { LoaderCircleDuotone } from './icons/LoaderCircleDuotone';
export { LoaderCircleFill } from './icons/LoaderCircleFill';
export { LoaderCircle } from './icons/LoaderCircle';
export { LockDuotone } from './icons/LockDuotone';
export { LockFill } from './icons/LockFill';
export { Lock } from './icons/Lock';
export { LogOutDuotone } from './icons/LogOutDuotone';
export { LogOutFill } from './icons/LogOutFill';
export { LogOut } from './icons/LogOut';
export { MailDuotone } from './icons/MailDuotone';
export { MailFill } from './icons/MailFill';
export { MailMoveDuotone } from './icons/MailMoveDuotone';
export { MailMoveFill } from './icons/MailMoveFill';
export { MailMove } from './icons/MailMove';
export { MailPlusDuotone } from './icons/MailPlusDuotone';
export { MailPlusFill } from './icons/MailPlusFill';
export { MailPlus } from './icons/MailPlus';
export { Mail } from './icons/Mail';
export { MapPinDuotone } from './icons/MapPinDuotone';
export { MapPinFill } from './icons/MapPinFill';
export { MapPin } from './icons/MapPin';
export { MaximizeDuotone } from './icons/MaximizeDuotone';
export { MaximizeFill } from './icons/MaximizeFill';
export { Maximize } from './icons/Maximize';
export { MediaKitsDuotone } from './icons/MediaKitsDuotone';
export { MediaKitsFill } from './icons/MediaKitsFill';
export { MediaKits } from './icons/MediaKits';
export { MegaphoneActiveDuotone } from './icons/MegaphoneActiveDuotone';
export { MegaphoneActiveFill } from './icons/MegaphoneActiveFill';
export { MegaphoneActive } from './icons/MegaphoneActive';
export { MegaphoneDuotone } from './icons/MegaphoneDuotone';
export { MegaphoneFill } from './icons/MegaphoneFill';
export { Megaphone } from './icons/Megaphone';
export { MenuDuotone } from './icons/MenuDuotone';
export { MenuFill } from './icons/MenuFill';
export { Menu } from './icons/Menu';
export { MessageSquareDuotone } from './icons/MessageSquareDuotone';
export { MessageSquareFill } from './icons/MessageSquareFill';
export { MessageSquare } from './icons/MessageSquare';
export { MessagesSquareDuotone } from './icons/MessagesSquareDuotone';
export { MessagesSquareFill } from './icons/MessagesSquareFill';
export { MessagesSquare } from './icons/MessagesSquare';
export { MinusDuotone } from './icons/MinusDuotone';
export { MinusFill } from './icons/MinusFill';
export { Minus } from './icons/Minus';
export { MoonDuotone } from './icons/MoonDuotone';
export { MoonFill } from './icons/MoonFill';
export { Moon } from './icons/Moon';
export { MousePointerClickDuotone } from './icons/MousePointerClickDuotone';
export { MousePointerClickFill } from './icons/MousePointerClickFill';
export { MousePointerClick } from './icons/MousePointerClick';
export { MoveDuotone } from './icons/MoveDuotone';
export { MoveFill } from './icons/MoveFill';
export { Move } from './icons/Move';
export { PanelLeftDuotone } from './icons/PanelLeftDuotone';
export { PanelLeftFill } from './icons/PanelLeftFill';
export { PanelLeft } from './icons/PanelLeft';
export { PanelRightDuotone } from './icons/PanelRightDuotone';
export { PanelRightFill } from './icons/PanelRightFill';
export { PanelRight } from './icons/PanelRight';
export { PencilDuotone } from './icons/PencilDuotone';
export { PencilFill } from './icons/PencilFill';
export { Pencil } from './icons/Pencil';
export { PinDuotone } from './icons/PinDuotone';
export { PinFill } from './icons/PinFill';
export { Pin } from './icons/Pin';
export { PlayDuotone } from './icons/PlayDuotone';
export { PlayFill } from './icons/PlayFill';
export { Play } from './icons/Play';
export { PlusDuotone } from './icons/PlusDuotone';
export { PlusFill } from './icons/PlusFill';
export { Plus } from './icons/Plus';
export { ReachDuotone } from './icons/ReachDuotone';
export { ReachFill } from './icons/ReachFill';
export { Reach } from './icons/Reach';
export { ReelDuotone } from './icons/ReelDuotone';
export { ReelFill } from './icons/ReelFill';
export { Reel } from './icons/Reel';
export { RefreshCwDuotone } from './icons/RefreshCwDuotone';
export { RefreshCwFill } from './icons/RefreshCwFill';
export { RefreshCw } from './icons/RefreshCw';
export { RemoveFormattingDuotone } from './icons/RemoveFormattingDuotone';
export { RemoveFormattingFill } from './icons/RemoveFormattingFill';
export { RemoveFormatting } from './icons/RemoveFormatting';
export { ReplyDuotone } from './icons/ReplyDuotone';
export { ReplyFill } from './icons/ReplyFill';
export { Reply } from './icons/Reply';
export { RotateCwDuotone } from './icons/RotateCwDuotone';
export { RotateCwFill } from './icons/RotateCwFill';
export { RotateCw } from './icons/RotateCw';
export { Rows2Duotone } from './icons/Rows2Duotone';
export { Rows2Fill } from './icons/Rows2Fill';
export { Rows2 } from './icons/Rows2';
export { SaveDuotone } from './icons/SaveDuotone';
export { SaveFill } from './icons/SaveFill';
export { Save } from './icons/Save';
export { SearchDuotone } from './icons/SearchDuotone';
export { SearchFill } from './icons/SearchFill';
export { SearchUserDuotone } from './icons/SearchUserDuotone';
export { SearchUserFill } from './icons/SearchUserFill';
export { SearchUser } from './icons/SearchUser';
export { Search } from './icons/Search';
export { ShareDuotone } from './icons/ShareDuotone';
export { ShareFill } from './icons/ShareFill';
export { Share } from './icons/Share';
export { SlidersHorizontalDuotone } from './icons/SlidersHorizontalDuotone';
export { SlidersHorizontalFill } from './icons/SlidersHorizontalFill';
export { SlidersHorizontal } from './icons/SlidersHorizontal';
export { SmileDuotone } from './icons/SmileDuotone';
export { SmileFill } from './icons/SmileFill';
export { Smile } from './icons/Smile';
export { SparklesDuotone } from './icons/SparklesDuotone';
export { SparklesFill } from './icons/SparklesFill';
export { Sparkles } from './icons/Sparkles';
export { SquareDuotone } from './icons/SquareDuotone';
export { SquareFill } from './icons/SquareFill';
export { SquarePenDuotone } from './icons/SquarePenDuotone';
export { SquarePenFill } from './icons/SquarePenFill';
export { SquarePen } from './icons/SquarePen';
export { Square } from './icons/Square';
export { StarDuotone } from './icons/StarDuotone';
export { StarFill } from './icons/StarFill';
export { Star } from './icons/Star';
export { SunDuotone } from './icons/SunDuotone';
export { SunFill } from './icons/SunFill';
export { Sun } from './icons/Sun';
export { TextAlignCenterDuotone } from './icons/TextAlignCenterDuotone';
export { TextAlignCenterFill } from './icons/TextAlignCenterFill';
export { TextAlignCenter } from './icons/TextAlignCenter';
export { TextAlignEndDuotone } from './icons/TextAlignEndDuotone';
export { TextAlignEndFill } from './icons/TextAlignEndFill';
export { TextAlignEnd } from './icons/TextAlignEnd';
export { TextAlignJustifyDuotone } from './icons/TextAlignJustifyDuotone';
export { TextAlignJustifyFill } from './icons/TextAlignJustifyFill';
export { TextAlignJustify } from './icons/TextAlignJustify';
export { TextAlignStartDuotone } from './icons/TextAlignStartDuotone';
export { TextAlignStartFill } from './icons/TextAlignStartFill';
export { TextAlignStart } from './icons/TextAlignStart';
export { ThumbsDownDuotone } from './icons/ThumbsDownDuotone';
export { ThumbsDownFill } from './icons/ThumbsDownFill';
export { ThumbsDown } from './icons/ThumbsDown';
export { ThumbsUpDuotone } from './icons/ThumbsUpDuotone';
export { ThumbsUpFill } from './icons/ThumbsUpFill';
export { ThumbsUp } from './icons/ThumbsUp';
export { TrashDuotone } from './icons/TrashDuotone';
export { TrashFill } from './icons/TrashFill';
export { Trash } from './icons/Trash';
export { TrendingDownDuotone } from './icons/TrendingDownDuotone';
export { TrendingDownFill } from './icons/TrendingDownFill';
export { TrendingDown } from './icons/TrendingDown';
export { TrendingUpDuotone } from './icons/TrendingUpDuotone';
export { TrendingUpFill } from './icons/TrendingUpFill';
export { TrendingUp } from './icons/TrendingUp';
export { TriangleDownUpDuotone } from './icons/TriangleDownUpDuotone';
export { TriangleDownUpFill } from './icons/TriangleDownUpFill';
export { TriangleDownUp } from './icons/TriangleDownUp';
export { UnlinkDuotone } from './icons/UnlinkDuotone';
export { UnlinkFill } from './icons/UnlinkFill';
export { Unlink } from './icons/Unlink';
export { UnlockDuotone } from './icons/UnlockDuotone';
export { UnlockFill } from './icons/UnlockFill';
export { Unlock } from './icons/Unlock';
export { UploadDuotone } from './icons/UploadDuotone';
export { UploadFill } from './icons/UploadFill';
export { Upload } from './icons/Upload';
export { UserDuotone } from './icons/UserDuotone';
export { UserFill } from './icons/UserFill';
export { User } from './icons/User';
export { UsersDuotone } from './icons/UsersDuotone';
export { UsersFill } from './icons/UsersFill';
export { Users } from './icons/Users';
export { Volume2Duotone } from './icons/Volume2Duotone';
export { Volume2Fill } from './icons/Volume2Fill';
export { Volume2 } from './icons/Volume2';
export { VolumeOffDuotone } from './icons/VolumeOffDuotone';
export { VolumeOffFill } from './icons/VolumeOffFill';
export { VolumeOff } from './icons/VolumeOff';
export { AlertDuotone as AlertDuotoneIcon } from './icons/AlertDuotone';
export { AlertDuotone as FoamAlertDuotone } from './icons/AlertDuotone';
export { AlertFill as AlertFillIcon } from './icons/AlertFill';
export { AlertFill as FoamAlertFill } from './icons/AlertFill';
export { Alert as AlertIcon } from './icons/Alert';
export { Alert as FoamAlert } from './icons/Alert';
export { ArchiveArrowUpDuotone as ArchiveArrowUpDuotoneIcon } from './icons/ArchiveArrowUpDuotone';
export { ArchiveArrowUpDuotone as FoamArchiveArrowUpDuotone } from './icons/ArchiveArrowUpDuotone';
export { ArchiveArrowUpFill as ArchiveArrowUpFillIcon } from './icons/ArchiveArrowUpFill';
export { ArchiveArrowUpFill as FoamArchiveArrowUpFill } from './icons/ArchiveArrowUpFill';
export { ArchiveArrowUp as ArchiveArrowUpIcon } from './icons/ArchiveArrowUp';
export { ArchiveArrowUp as FoamArchiveArrowUp } from './icons/ArchiveArrowUp';
export { ArchiveDuotone as ArchiveDuotoneIcon } from './icons/ArchiveDuotone';
export { ArchiveDuotone as FoamArchiveDuotone } from './icons/ArchiveDuotone';
export { ArchiveFill as ArchiveFillIcon } from './icons/ArchiveFill';
export { ArchiveFill as FoamArchiveFill } from './icons/ArchiveFill';
export { Archive as ArchiveIcon } from './icons/Archive';
export { Archive as FoamArchive } from './icons/Archive';
export { ArrowDown01Duotone as ArrowDown01DuotoneIcon } from './icons/ArrowDown01Duotone';
export { ArrowDown01Duotone as FoamArrowDown01Duotone } from './icons/ArrowDown01Duotone';
export { ArrowDown01Fill as ArrowDown01FillIcon } from './icons/ArrowDown01Fill';
export { ArrowDown01Fill as FoamArrowDown01Fill } from './icons/ArrowDown01Fill';
export { ArrowDown01 as ArrowDown01Icon } from './icons/ArrowDown01';
export { ArrowDown01 as FoamArrowDown01 } from './icons/ArrowDown01';
export { ArrowDown10Duotone as ArrowDown10DuotoneIcon } from './icons/ArrowDown10Duotone';
export { ArrowDown10Duotone as FoamArrowDown10Duotone } from './icons/ArrowDown10Duotone';
export { ArrowDown10Fill as ArrowDown10FillIcon } from './icons/ArrowDown10Fill';
export { ArrowDown10Fill as FoamArrowDown10Fill } from './icons/ArrowDown10Fill';
export { ArrowDown10 as ArrowDown10Icon } from './icons/ArrowDown10';
export { ArrowDown10 as FoamArrowDown10 } from './icons/ArrowDown10';
export { ArrowDownIGDuotone as ArrowDownIGDuotoneIcon } from './icons/ArrowDownIGDuotone';
export { ArrowDownIGDuotone as FoamArrowDownIGDuotone } from './icons/ArrowDownIGDuotone';
export { ArrowDownIGFill as ArrowDownIGFillIcon } from './icons/ArrowDownIGFill';
export { ArrowDownIGFill as FoamArrowDownIGFill } from './icons/ArrowDownIGFill';
export { ArrowDownIG as ArrowDownIGIcon } from './icons/ArrowDownIG';
export { ArrowDownIG as FoamArrowDownIG } from './icons/ArrowDownIG';
export { ArrowDownSCDuotone as ArrowDownSCDuotoneIcon } from './icons/ArrowDownSCDuotone';
export { ArrowDownSCDuotone as FoamArrowDownSCDuotone } from './icons/ArrowDownSCDuotone';
export { ArrowDownSCFill as ArrowDownSCFillIcon } from './icons/ArrowDownSCFill';
export { ArrowDownSCFill as FoamArrowDownSCFill } from './icons/ArrowDownSCFill';
export { ArrowDownSC as ArrowDownSCIcon } from './icons/ArrowDownSC';
export { ArrowDownSC as FoamArrowDownSC } from './icons/ArrowDownSC';
export { ArrowDownTTDuotone as ArrowDownTTDuotoneIcon } from './icons/ArrowDownTTDuotone';
export { ArrowDownTTDuotone as FoamArrowDownTTDuotone } from './icons/ArrowDownTTDuotone';
export { ArrowDownTTFill as ArrowDownTTFillIcon } from './icons/ArrowDownTTFill';
export { ArrowDownTTFill as FoamArrowDownTTFill } from './icons/ArrowDownTTFill';
export { ArrowDownTT as ArrowDownTTIcon } from './icons/ArrowDownTT';
export { ArrowDownTT as FoamArrowDownTT } from './icons/ArrowDownTT';
export { ArrowDownYTDuotone as ArrowDownYTDuotoneIcon } from './icons/ArrowDownYTDuotone';
export { ArrowDownYTDuotone as FoamArrowDownYTDuotone } from './icons/ArrowDownYTDuotone';
export { ArrowDownYTFill as ArrowDownYTFillIcon } from './icons/ArrowDownYTFill';
export { ArrowDownYTFill as FoamArrowDownYTFill } from './icons/ArrowDownYTFill';
export { ArrowDownYT as ArrowDownYTIcon } from './icons/ArrowDownYT';
export { ArrowDownYT as FoamArrowDownYT } from './icons/ArrowDownYT';
export { ArrowDownDuotone as ArrowDownDuotoneIcon } from './icons/ArrowDownDuotone';
export { ArrowDownDuotone as FoamArrowDownDuotone } from './icons/ArrowDownDuotone';
export { ArrowDownFill as ArrowDownFillIcon } from './icons/ArrowDownFill';
export { ArrowDownFill as FoamArrowDownFill } from './icons/ArrowDownFill';
export { ArrowDownNarrowWideDuotone as ArrowDownNarrowWideDuotoneIcon } from './icons/ArrowDownNarrowWideDuotone';
export { ArrowDownNarrowWideDuotone as FoamArrowDownNarrowWideDuotone } from './icons/ArrowDownNarrowWideDuotone';
export { ArrowDownNarrowWideFill as ArrowDownNarrowWideFillIcon } from './icons/ArrowDownNarrowWideFill';
export { ArrowDownNarrowWideFill as FoamArrowDownNarrowWideFill } from './icons/ArrowDownNarrowWideFill';
export { ArrowDownNarrowWide as ArrowDownNarrowWideIcon } from './icons/ArrowDownNarrowWide';
export { ArrowDownNarrowWide as FoamArrowDownNarrowWide } from './icons/ArrowDownNarrowWide';
export { ArrowDownUpDuotone as ArrowDownUpDuotoneIcon } from './icons/ArrowDownUpDuotone';
export { ArrowDownUpDuotone as FoamArrowDownUpDuotone } from './icons/ArrowDownUpDuotone';
export { ArrowDownUpFill as ArrowDownUpFillIcon } from './icons/ArrowDownUpFill';
export { ArrowDownUpFill as FoamArrowDownUpFill } from './icons/ArrowDownUpFill';
export { ArrowDownUp as ArrowDownUpIcon } from './icons/ArrowDownUp';
export { ArrowDownUp as FoamArrowDownUp } from './icons/ArrowDownUp';
export { ArrowDownWideNarrowDuotone as ArrowDownWideNarrowDuotoneIcon } from './icons/ArrowDownWideNarrowDuotone';
export { ArrowDownWideNarrowDuotone as FoamArrowDownWideNarrowDuotone } from './icons/ArrowDownWideNarrowDuotone';
export { ArrowDownWideNarrowFill as ArrowDownWideNarrowFillIcon } from './icons/ArrowDownWideNarrowFill';
export { ArrowDownWideNarrowFill as FoamArrowDownWideNarrowFill } from './icons/ArrowDownWideNarrowFill';
export { ArrowDownWideNarrow as ArrowDownWideNarrowIcon } from './icons/ArrowDownWideNarrow';
export { ArrowDownWideNarrow as FoamArrowDownWideNarrow } from './icons/ArrowDownWideNarrow';
export { ArrowDown as ArrowDownIcon } from './icons/ArrowDown';
export { ArrowDown as FoamArrowDown } from './icons/ArrowDown';
export { ArrowLeftDuotone as ArrowLeftDuotoneIcon } from './icons/ArrowLeftDuotone';
export { ArrowLeftDuotone as FoamArrowLeftDuotone } from './icons/ArrowLeftDuotone';
export { ArrowLeftFill as ArrowLeftFillIcon } from './icons/ArrowLeftFill';
export { ArrowLeftFill as FoamArrowLeftFill } from './icons/ArrowLeftFill';
export { ArrowLeft as ArrowLeftIcon } from './icons/ArrowLeft';
export { ArrowLeft as FoamArrowLeft } from './icons/ArrowLeft';
export { ArrowRightDuotone as ArrowRightDuotoneIcon } from './icons/ArrowRightDuotone';
export { ArrowRightDuotone as FoamArrowRightDuotone } from './icons/ArrowRightDuotone';
export { ArrowRightFill as ArrowRightFillIcon } from './icons/ArrowRightFill';
export { ArrowRightFill as FoamArrowRightFill } from './icons/ArrowRightFill';
export { ArrowRightToLineDuotone as ArrowRightToLineDuotoneIcon } from './icons/ArrowRightToLineDuotone';
export { ArrowRightToLineDuotone as FoamArrowRightToLineDuotone } from './icons/ArrowRightToLineDuotone';
export { ArrowRightToLineFill as ArrowRightToLineFillIcon } from './icons/ArrowRightToLineFill';
export { ArrowRightToLineFill as FoamArrowRightToLineFill } from './icons/ArrowRightToLineFill';
export { ArrowRightToLine as ArrowRightToLineIcon } from './icons/ArrowRightToLine';
export { ArrowRightToLine as FoamArrowRightToLine } from './icons/ArrowRightToLine';
export { ArrowRight as ArrowRightIcon } from './icons/ArrowRight';
export { ArrowRight as FoamArrowRight } from './icons/ArrowRight';
export { ArrowUpIGDuotone as ArrowUpIGDuotoneIcon } from './icons/ArrowUpIGDuotone';
export { ArrowUpIGDuotone as FoamArrowUpIGDuotone } from './icons/ArrowUpIGDuotone';
export { ArrowUpIGFill as ArrowUpIGFillIcon } from './icons/ArrowUpIGFill';
export { ArrowUpIGFill as FoamArrowUpIGFill } from './icons/ArrowUpIGFill';
export { ArrowUpIG as ArrowUpIGIcon } from './icons/ArrowUpIG';
export { ArrowUpIG as FoamArrowUpIG } from './icons/ArrowUpIG';
export { ArrowUpSCDuotone as ArrowUpSCDuotoneIcon } from './icons/ArrowUpSCDuotone';
export { ArrowUpSCDuotone as FoamArrowUpSCDuotone } from './icons/ArrowUpSCDuotone';
export { ArrowUpSCFill as ArrowUpSCFillIcon } from './icons/ArrowUpSCFill';
export { ArrowUpSCFill as FoamArrowUpSCFill } from './icons/ArrowUpSCFill';
export { ArrowUpSC as ArrowUpSCIcon } from './icons/ArrowUpSC';
export { ArrowUpSC as FoamArrowUpSC } from './icons/ArrowUpSC';
export { ArrowUpTTDuotone as ArrowUpTTDuotoneIcon } from './icons/ArrowUpTTDuotone';
export { ArrowUpTTDuotone as FoamArrowUpTTDuotone } from './icons/ArrowUpTTDuotone';
export { ArrowUpTTFill as ArrowUpTTFillIcon } from './icons/ArrowUpTTFill';
export { ArrowUpTTFill as FoamArrowUpTTFill } from './icons/ArrowUpTTFill';
export { ArrowUpTT as ArrowUpTTIcon } from './icons/ArrowUpTT';
export { ArrowUpTT as FoamArrowUpTT } from './icons/ArrowUpTT';
export { ArrowUpYTDuotone as ArrowUpYTDuotoneIcon } from './icons/ArrowUpYTDuotone';
export { ArrowUpYTDuotone as FoamArrowUpYTDuotone } from './icons/ArrowUpYTDuotone';
export { ArrowUpYTFill as ArrowUpYTFillIcon } from './icons/ArrowUpYTFill';
export { ArrowUpYTFill as FoamArrowUpYTFill } from './icons/ArrowUpYTFill';
export { ArrowUpYT as ArrowUpYTIcon } from './icons/ArrowUpYT';
export { ArrowUpYT as FoamArrowUpYT } from './icons/ArrowUpYT';
export { ArrowUpAZDuotone as ArrowUpAZDuotoneIcon } from './icons/ArrowUpAZDuotone';
export { ArrowUpAZDuotone as FoamArrowUpAZDuotone } from './icons/ArrowUpAZDuotone';
export { ArrowUpAZFill as ArrowUpAZFillIcon } from './icons/ArrowUpAZFill';
export { ArrowUpAZFill as FoamArrowUpAZFill } from './icons/ArrowUpAZFill';
export { ArrowUpAZ as ArrowUpAZIcon } from './icons/ArrowUpAZ';
export { ArrowUpAZ as FoamArrowUpAZ } from './icons/ArrowUpAZ';
export { ArrowUpDuotone as ArrowUpDuotoneIcon } from './icons/ArrowUpDuotone';
export { ArrowUpDuotone as FoamArrowUpDuotone } from './icons/ArrowUpDuotone';
export { ArrowUpFill as ArrowUpFillIcon } from './icons/ArrowUpFill';
export { ArrowUpFill as FoamArrowUpFill } from './icons/ArrowUpFill';
export { ArrowUpNarrowWideDuotone as ArrowUpNarrowWideDuotoneIcon } from './icons/ArrowUpNarrowWideDuotone';
export { ArrowUpNarrowWideDuotone as FoamArrowUpNarrowWideDuotone } from './icons/ArrowUpNarrowWideDuotone';
export { ArrowUpNarrowWideFill as ArrowUpNarrowWideFillIcon } from './icons/ArrowUpNarrowWideFill';
export { ArrowUpNarrowWideFill as FoamArrowUpNarrowWideFill } from './icons/ArrowUpNarrowWideFill';
export { ArrowUpNarrowWide as ArrowUpNarrowWideIcon } from './icons/ArrowUpNarrowWide';
export { ArrowUpNarrowWide as FoamArrowUpNarrowWide } from './icons/ArrowUpNarrowWide';
export { ArrowUpWideNarrowDuotone as ArrowUpWideNarrowDuotoneIcon } from './icons/ArrowUpWideNarrowDuotone';
export { ArrowUpWideNarrowDuotone as FoamArrowUpWideNarrowDuotone } from './icons/ArrowUpWideNarrowDuotone';
export { ArrowUpWideNarrowFill as ArrowUpWideNarrowFillIcon } from './icons/ArrowUpWideNarrowFill';
export { ArrowUpWideNarrowFill as FoamArrowUpWideNarrowFill } from './icons/ArrowUpWideNarrowFill';
export { ArrowUpWideNarrow as ArrowUpWideNarrowIcon } from './icons/ArrowUpWideNarrow';
export { ArrowUpWideNarrow as FoamArrowUpWideNarrow } from './icons/ArrowUpWideNarrow';
export { ArrowUpZADuotone as ArrowUpZADuotoneIcon } from './icons/ArrowUpZADuotone';
export { ArrowUpZADuotone as FoamArrowUpZADuotone } from './icons/ArrowUpZADuotone';
export { ArrowUpZAFill as ArrowUpZAFillIcon } from './icons/ArrowUpZAFill';
export { ArrowUpZAFill as FoamArrowUpZAFill } from './icons/ArrowUpZAFill';
export { ArrowUpZA as ArrowUpZAIcon } from './icons/ArrowUpZA';
export { ArrowUpZA as FoamArrowUpZA } from './icons/ArrowUpZA';
export { ArrowUp as ArrowUpIcon } from './icons/ArrowUp';
export { ArrowUp as FoamArrowUp } from './icons/ArrowUp';
export { BanDuotone as BanDuotoneIcon } from './icons/BanDuotone';
export { BanDuotone as FoamBanDuotone } from './icons/BanDuotone';
export { BanFill as BanFillIcon } from './icons/BanFill';
export { BanFill as FoamBanFill } from './icons/BanFill';
export { Ban as BanIcon } from './icons/Ban';
export { Ban as FoamBan } from './icons/Ban';
export { BellDuotone as BellDuotoneIcon } from './icons/BellDuotone';
export { BellDuotone as FoamBellDuotone } from './icons/BellDuotone';
export { BellFill as BellFillIcon } from './icons/BellFill';
export { BellFill as FoamBellFill } from './icons/BellFill';
export { Bell as BellIcon } from './icons/Bell';
export { Bell as FoamBell } from './icons/Bell';
export { BoldDuotone as BoldDuotoneIcon } from './icons/BoldDuotone';
export { BoldDuotone as FoamBoldDuotone } from './icons/BoldDuotone';
export { BoldFill as BoldFillIcon } from './icons/BoldFill';
export { BoldFill as FoamBoldFill } from './icons/BoldFill';
export { Bold as BoldIcon } from './icons/Bold';
export { Bold as FoamBold } from './icons/Bold';
export { BookmarkDuotone as BookmarkDuotoneIcon } from './icons/BookmarkDuotone';
export { BookmarkDuotone as FoamBookmarkDuotone } from './icons/BookmarkDuotone';
export { BookmarkFill as BookmarkFillIcon } from './icons/BookmarkFill';
export { BookmarkFill as FoamBookmarkFill } from './icons/BookmarkFill';
export { Bookmark as BookmarkIcon } from './icons/Bookmark';
export { Bookmark as FoamBookmark } from './icons/Bookmark';
export { CalendarDuotone as CalendarDuotoneIcon } from './icons/CalendarDuotone';
export { CalendarDuotone as FoamCalendarDuotone } from './icons/CalendarDuotone';
export { CalendarFill as CalendarFillIcon } from './icons/CalendarFill';
export { CalendarFill as FoamCalendarFill } from './icons/CalendarFill';
export { Calendar as CalendarIcon } from './icons/Calendar';
export { Calendar as FoamCalendar } from './icons/Calendar';
export { ChartColumnSquareDuotone as ChartColumnSquareDuotoneIcon } from './icons/ChartColumnSquareDuotone';
export { ChartColumnSquareDuotone as FoamChartColumnSquareDuotone } from './icons/ChartColumnSquareDuotone';
export { ChartColumnSquareFill as ChartColumnSquareFillIcon } from './icons/ChartColumnSquareFill';
export { ChartColumnSquareFill as FoamChartColumnSquareFill } from './icons/ChartColumnSquareFill';
export { ChartColumnSquare as ChartColumnSquareIcon } from './icons/ChartColumnSquare';
export { ChartColumnSquare as FoamChartColumnSquare } from './icons/ChartColumnSquare';
export { CheckboxDuotone as CheckboxDuotoneIcon } from './icons/CheckboxDuotone';
export { CheckboxDuotone as FoamCheckboxDuotone } from './icons/CheckboxDuotone';
export { CheckboxFill as CheckboxFillIcon } from './icons/CheckboxFill';
export { CheckboxFill as FoamCheckboxFill } from './icons/CheckboxFill';
export { Checkbox as CheckboxIcon } from './icons/Checkbox';
export { Checkbox as FoamCheckbox } from './icons/Checkbox';
export { CheckmarkDuotone as CheckmarkDuotoneIcon } from './icons/CheckmarkDuotone';
export { CheckmarkDuotone as FoamCheckmarkDuotone } from './icons/CheckmarkDuotone';
export { CheckmarkFill as CheckmarkFillIcon } from './icons/CheckmarkFill';
export { CheckmarkFill as FoamCheckmarkFill } from './icons/CheckmarkFill';
export { Checkmark as CheckmarkIcon } from './icons/Checkmark';
export { Checkmark as FoamCheckmark } from './icons/Checkmark';
export { ChevronDownDuotone as ChevronDownDuotoneIcon } from './icons/ChevronDownDuotone';
export { ChevronDownDuotone as FoamChevronDownDuotone } from './icons/ChevronDownDuotone';
export { ChevronDownFill as ChevronDownFillIcon } from './icons/ChevronDownFill';
export { ChevronDownFill as FoamChevronDownFill } from './icons/ChevronDownFill';
export { ChevronDown as ChevronDownIcon } from './icons/ChevronDown';
export { ChevronDown as FoamChevronDown } from './icons/ChevronDown';
export { ChevronLeftDuotone as ChevronLeftDuotoneIcon } from './icons/ChevronLeftDuotone';
export { ChevronLeftDuotone as FoamChevronLeftDuotone } from './icons/ChevronLeftDuotone';
export { ChevronLeftFill as ChevronLeftFillIcon } from './icons/ChevronLeftFill';
export { ChevronLeftFill as FoamChevronLeftFill } from './icons/ChevronLeftFill';
export { ChevronLeft as ChevronLeftIcon } from './icons/ChevronLeft';
export { ChevronLeft as FoamChevronLeft } from './icons/ChevronLeft';
export { ChevronRightDuotone as ChevronRightDuotoneIcon } from './icons/ChevronRightDuotone';
export { ChevronRightDuotone as FoamChevronRightDuotone } from './icons/ChevronRightDuotone';
export { ChevronRightFill as ChevronRightFillIcon } from './icons/ChevronRightFill';
export { ChevronRightFill as FoamChevronRightFill } from './icons/ChevronRightFill';
export { ChevronRight as ChevronRightIcon } from './icons/ChevronRight';
export { ChevronRight as FoamChevronRight } from './icons/ChevronRight';
export { ChevronUpDuotone as ChevronUpDuotoneIcon } from './icons/ChevronUpDuotone';
export { ChevronUpDuotone as FoamChevronUpDuotone } from './icons/ChevronUpDuotone';
export { ChevronUpFill as ChevronUpFillIcon } from './icons/ChevronUpFill';
export { ChevronUpFill as FoamChevronUpFill } from './icons/ChevronUpFill';
export { ChevronUp as ChevronUpIcon } from './icons/ChevronUp';
export { ChevronUp as FoamChevronUp } from './icons/ChevronUp';
export { CircleAlertDuotone as CircleAlertDuotoneIcon } from './icons/CircleAlertDuotone';
export { CircleAlertDuotone as FoamCircleAlertDuotone } from './icons/CircleAlertDuotone';
export { CircleAlertFill as CircleAlertFillIcon } from './icons/CircleAlertFill';
export { CircleAlertFill as FoamCircleAlertFill } from './icons/CircleAlertFill';
export { CircleAlert as CircleAlertIcon } from './icons/CircleAlert';
export { CircleAlert as FoamCircleAlert } from './icons/CircleAlert';
export { CircleDollarSignDuotone as CircleDollarSignDuotoneIcon } from './icons/CircleDollarSignDuotone';
export { CircleDollarSignDuotone as FoamCircleDollarSignDuotone } from './icons/CircleDollarSignDuotone';
export { CircleDollarSignFill as CircleDollarSignFillIcon } from './icons/CircleDollarSignFill';
export { CircleDollarSignFill as FoamCircleDollarSignFill } from './icons/CircleDollarSignFill';
export { CircleDollarSign as CircleDollarSignIcon } from './icons/CircleDollarSign';
export { CircleDollarSign as FoamCircleDollarSign } from './icons/CircleDollarSign';
export { CircleQuestionMarkDuotone as CircleQuestionMarkDuotoneIcon } from './icons/CircleQuestionMarkDuotone';
export { CircleQuestionMarkDuotone as FoamCircleQuestionMarkDuotone } from './icons/CircleQuestionMarkDuotone';
export { CircleQuestionMarkFill as CircleQuestionMarkFillIcon } from './icons/CircleQuestionMarkFill';
export { CircleQuestionMarkFill as FoamCircleQuestionMarkFill } from './icons/CircleQuestionMarkFill';
export { CircleQuestionMark as CircleQuestionMarkIcon } from './icons/CircleQuestionMark';
export { CircleQuestionMark as FoamCircleQuestionMark } from './icons/CircleQuestionMark';
export { CircleXDuotone as CircleXDuotoneIcon } from './icons/CircleXDuotone';
export { CircleXDuotone as FoamCircleXDuotone } from './icons/CircleXDuotone';
export { CircleXFill as CircleXFillIcon } from './icons/CircleXFill';
export { CircleXFill as FoamCircleXFill } from './icons/CircleXFill';
export { CircleX as CircleXIcon } from './icons/CircleX';
export { CircleX as FoamCircleX } from './icons/CircleX';
export { ClockArrowDown1 as ClockArrowDown1Icon } from './icons/ClockArrowDown1';
export { ClockArrowDown1 as FoamClockArrowDown1 } from './icons/ClockArrowDown1';
export { ClockArrowDownDuotone as ClockArrowDownDuotoneIcon } from './icons/ClockArrowDownDuotone';
export { ClockArrowDownDuotone as FoamClockArrowDownDuotone } from './icons/ClockArrowDownDuotone';
export { ClockArrowDownFill as ClockArrowDownFillIcon } from './icons/ClockArrowDownFill';
export { ClockArrowDownFill as FoamClockArrowDownFill } from './icons/ClockArrowDownFill';
export { ClockArrowDown as ClockArrowDownIcon } from './icons/ClockArrowDown';
export { ClockArrowDown as FoamClockArrowDown } from './icons/ClockArrowDown';
export { ClockArrowUp1 as ClockArrowUp1Icon } from './icons/ClockArrowUp1';
export { ClockArrowUp1 as FoamClockArrowUp1 } from './icons/ClockArrowUp1';
export { ClockArrowUpDuotone as ClockArrowUpDuotoneIcon } from './icons/ClockArrowUpDuotone';
export { ClockArrowUpDuotone as FoamClockArrowUpDuotone } from './icons/ClockArrowUpDuotone';
export { ClockArrowUpFill as ClockArrowUpFillIcon } from './icons/ClockArrowUpFill';
export { ClockArrowUpFill as FoamClockArrowUpFill } from './icons/ClockArrowUpFill';
export { ClockArrowUp as ClockArrowUpIcon } from './icons/ClockArrowUp';
export { ClockArrowUp as FoamClockArrowUp } from './icons/ClockArrowUp';
export { ClockDuotone as ClockDuotoneIcon } from './icons/ClockDuotone';
export { ClockDuotone as FoamClockDuotone } from './icons/ClockDuotone';
export { ClockFill as ClockFillIcon } from './icons/ClockFill';
export { ClockFill as FoamClockFill } from './icons/ClockFill';
export { Clock as ClockIcon } from './icons/Clock';
export { Clock as FoamClock } from './icons/Clock';
export { CogDuotone as CogDuotoneIcon } from './icons/CogDuotone';
export { CogDuotone as FoamCogDuotone } from './icons/CogDuotone';
export { CogFill as CogFillIcon } from './icons/CogFill';
export { CogFill as FoamCogFill } from './icons/CogFill';
export { Cog as CogIcon } from './icons/Cog';
export { Cog as FoamCog } from './icons/Cog';
export { Columns3Duotone as Columns3DuotoneIcon } from './icons/Columns3Duotone';
export { Columns3Duotone as FoamColumns3Duotone } from './icons/Columns3Duotone';
export { Columns3Fill as Columns3FillIcon } from './icons/Columns3Fill';
export { Columns3Fill as FoamColumns3Fill } from './icons/Columns3Fill';
export { Columns3 as Columns3Icon } from './icons/Columns3';
export { Columns3 as FoamColumns3 } from './icons/Columns3';
export { CommandDuotone as CommandDuotoneIcon } from './icons/CommandDuotone';
export { CommandDuotone as FoamCommandDuotone } from './icons/CommandDuotone';
export { CommandFill as CommandFillIcon } from './icons/CommandFill';
export { CommandFill as FoamCommandFill } from './icons/CommandFill';
export { Command as CommandIcon } from './icons/Command';
export { Command as FoamCommand } from './icons/Command';
export { ContentPlusDuotone as ContentPlusDuotoneIcon } from './icons/ContentPlusDuotone';
export { ContentPlusDuotone as FoamContentPlusDuotone } from './icons/ContentPlusDuotone';
export { ContentPlusFill as ContentPlusFillIcon } from './icons/ContentPlusFill';
export { ContentPlusFill as FoamContentPlusFill } from './icons/ContentPlusFill';
export { ContentPlus as ContentPlusIcon } from './icons/ContentPlus';
export { ContentPlus as FoamContentPlus } from './icons/ContentPlus';
export { CopyDuotone as CopyDuotoneIcon } from './icons/CopyDuotone';
export { CopyDuotone as FoamCopyDuotone } from './icons/CopyDuotone';
export { CopyFill as CopyFillIcon } from './icons/CopyFill';
export { CopyFill as FoamCopyFill } from './icons/CopyFill';
export { Copy as CopyIcon } from './icons/Copy';
export { Copy as FoamCopy } from './icons/Copy';
export { DownloadDuotone as DownloadDuotoneIcon } from './icons/DownloadDuotone';
export { DownloadDuotone as FoamDownloadDuotone } from './icons/DownloadDuotone';
export { DownloadFill as DownloadFillIcon } from './icons/DownloadFill';
export { DownloadFill as FoamDownloadFill } from './icons/DownloadFill';
export { Download as DownloadIcon } from './icons/Download';
export { Download as FoamDownload } from './icons/Download';
export { EclipseDuotone as EclipseDuotoneIcon } from './icons/EclipseDuotone';
export { EclipseDuotone as FoamEclipseDuotone } from './icons/EclipseDuotone';
export { EclipseFill as EclipseFillIcon } from './icons/EclipseFill';
export { EclipseFill as FoamEclipseFill } from './icons/EclipseFill';
export { Eclipse as EclipseIcon } from './icons/Eclipse';
export { Eclipse as FoamEclipse } from './icons/Eclipse';
export { ExternalLinkDuotone as ExternalLinkDuotoneIcon } from './icons/ExternalLinkDuotone';
export { ExternalLinkDuotone as FoamExternalLinkDuotone } from './icons/ExternalLinkDuotone';
export { ExternalLinkFill as ExternalLinkFillIcon } from './icons/ExternalLinkFill';
export { ExternalLinkFill as FoamExternalLinkFill } from './icons/ExternalLinkFill';
export { ExternalLink as ExternalLinkIcon } from './icons/ExternalLink';
export { ExternalLink as FoamExternalLink } from './icons/ExternalLink';
export { EyeDuotone as EyeDuotoneIcon } from './icons/EyeDuotone';
export { EyeDuotone as FoamEyeDuotone } from './icons/EyeDuotone';
export { EyeFill as EyeFillIcon } from './icons/EyeFill';
export { EyeFill as FoamEyeFill } from './icons/EyeFill';
export { EyeOffDuotone as EyeOffDuotoneIcon } from './icons/EyeOffDuotone';
export { EyeOffDuotone as FoamEyeOffDuotone } from './icons/EyeOffDuotone';
export { EyeOffFill as EyeOffFillIcon } from './icons/EyeOffFill';
export { EyeOffFill as FoamEyeOffFill } from './icons/EyeOffFill';
export { EyeOff as EyeOffIcon } from './icons/EyeOff';
export { EyeOff as FoamEyeOff } from './icons/EyeOff';
export { Eye as EyeIcon } from './icons/Eye';
export { Eye as FoamEye } from './icons/Eye';
export { FlameDuotone as FlameDuotoneIcon } from './icons/FlameDuotone';
export { FlameDuotone as FoamFlameDuotone } from './icons/FlameDuotone';
export { FlameFill as FlameFillIcon } from './icons/FlameFill';
export { FlameFill as FoamFlameFill } from './icons/FlameFill';
export { Flame as FlameIcon } from './icons/Flame';
export { Flame as FoamFlame } from './icons/Flame';
export { FrownDuotone as FrownDuotoneIcon } from './icons/FrownDuotone';
export { FrownDuotone as FoamFrownDuotone } from './icons/FrownDuotone';
export { FrownFill as FrownFillIcon } from './icons/FrownFill';
export { FrownFill as FoamFrownFill } from './icons/FrownFill';
export { Frown as FrownIcon } from './icons/Frown';
export { Frown as FoamFrown } from './icons/Frown';
export { FullscreenDuotone as FullscreenDuotoneIcon } from './icons/FullscreenDuotone';
export { FullscreenDuotone as FoamFullscreenDuotone } from './icons/FullscreenDuotone';
export { FullscreenFill as FullscreenFillIcon } from './icons/FullscreenFill';
export { FullscreenFill as FoamFullscreenFill } from './icons/FullscreenFill';
export { Fullscreen as FullscreenIcon } from './icons/Fullscreen';
export { Fullscreen as FoamFullscreen } from './icons/Fullscreen';
export { GlobeDuotone as GlobeDuotoneIcon } from './icons/GlobeDuotone';
export { GlobeDuotone as FoamGlobeDuotone } from './icons/GlobeDuotone';
export { GlobeFill as GlobeFillIcon } from './icons/GlobeFill';
export { GlobeFill as FoamGlobeFill } from './icons/GlobeFill';
export { Globe as GlobeIcon } from './icons/Globe';
export { Globe as FoamGlobe } from './icons/Globe';
export { Grid1x2Duotone as Grid1x2DuotoneIcon } from './icons/Grid1x2Duotone';
export { Grid1x2Duotone as FoamGrid1x2Duotone } from './icons/Grid1x2Duotone';
export { Grid1x2Fill as Grid1x2FillIcon } from './icons/Grid1x2Fill';
export { Grid1x2Fill as FoamGrid1x2Fill } from './icons/Grid1x2Fill';
export { Grid1x2 as Grid1x2Icon } from './icons/Grid1x2';
export { Grid1x2 as FoamGrid1x2 } from './icons/Grid1x2';
export { Grid2x2Duotone as Grid2x2DuotoneIcon } from './icons/Grid2x2Duotone';
export { Grid2x2Duotone as FoamGrid2x2Duotone } from './icons/Grid2x2Duotone';
export { Grid2x2Fill as Grid2x2FillIcon } from './icons/Grid2x2Fill';
export { Grid2x2Fill as FoamGrid2x2Fill } from './icons/Grid2x2Fill';
export { Grid2x2 as Grid2x2Icon } from './icons/Grid2x2';
export { Grid2x2 as FoamGrid2x2 } from './icons/Grid2x2';
export { HistoryDuotone as HistoryDuotoneIcon } from './icons/HistoryDuotone';
export { HistoryDuotone as FoamHistoryDuotone } from './icons/HistoryDuotone';
export { HistoryFill as HistoryFillIcon } from './icons/HistoryFill';
export { HistoryFill as FoamHistoryFill } from './icons/HistoryFill';
export { History as HistoryIcon } from './icons/History';
export { History as FoamHistory } from './icons/History';
export { HotspotDuotone as HotspotDuotoneIcon } from './icons/HotspotDuotone';
export { HotspotDuotone as FoamHotspotDuotone } from './icons/HotspotDuotone';
export { HotspotFill as HotspotFillIcon } from './icons/HotspotFill';
export { HotspotFill as FoamHotspotFill } from './icons/HotspotFill';
export { Hotspot as HotspotIcon } from './icons/Hotspot';
export { Hotspot as FoamHotspot } from './icons/Hotspot';
export { HouseDuotone as HouseDuotoneIcon } from './icons/HouseDuotone';
export { HouseDuotone as FoamHouseDuotone } from './icons/HouseDuotone';
export { HouseFill as HouseFillIcon } from './icons/HouseFill';
export { HouseFill as FoamHouseFill } from './icons/HouseFill';
export { House as HouseIcon } from './icons/House';
export { House as FoamHouse } from './icons/House';
export { ImageDuotone as ImageDuotoneIcon } from './icons/ImageDuotone';
export { ImageDuotone as FoamImageDuotone } from './icons/ImageDuotone';
export { ImageFill as ImageFillIcon } from './icons/ImageFill';
export { ImageFill as FoamImageFill } from './icons/ImageFill';
export { Image as ImageIcon } from './icons/Image';
export { Image as FoamImage } from './icons/Image';
export { ImagesDuotone as ImagesDuotoneIcon } from './icons/ImagesDuotone';
export { ImagesDuotone as FoamImagesDuotone } from './icons/ImagesDuotone';
export { ImagesFill as ImagesFillIcon } from './icons/ImagesFill';
export { ImagesFill as FoamImagesFill } from './icons/ImagesFill';
export { Images as ImagesIcon } from './icons/Images';
export { Images as FoamImages } from './icons/Images';
export { InboxDuotone as InboxDuotoneIcon } from './icons/InboxDuotone';
export { InboxDuotone as FoamInboxDuotone } from './icons/InboxDuotone';
export { InboxFill as InboxFillIcon } from './icons/InboxFill';
export { InboxFill as FoamInboxFill } from './icons/InboxFill';
export { Inbox as InboxIcon } from './icons/Inbox';
export { Inbox as FoamInbox } from './icons/Inbox';
export { InfoDuotone as InfoDuotoneIcon } from './icons/InfoDuotone';
export { InfoDuotone as FoamInfoDuotone } from './icons/InfoDuotone';
export { InfoFill as InfoFillIcon } from './icons/InfoFill';
export { InfoFill as FoamInfoFill } from './icons/InfoFill';
export { Info as InfoIcon } from './icons/Info';
export { Info as FoamInfo } from './icons/Info';
export { ItalicDuotone as ItalicDuotoneIcon } from './icons/ItalicDuotone';
export { ItalicDuotone as FoamItalicDuotone } from './icons/ItalicDuotone';
export { ItalicFill as ItalicFillIcon } from './icons/ItalicFill';
export { ItalicFill as FoamItalicFill } from './icons/ItalicFill';
export { Italic as ItalicIcon } from './icons/Italic';
export { Italic as FoamItalic } from './icons/Italic';
export { LinkDuotone as LinkDuotoneIcon } from './icons/LinkDuotone';
export { LinkDuotone as FoamLinkDuotone } from './icons/LinkDuotone';
export { LinkFill as LinkFillIcon } from './icons/LinkFill';
export { LinkFill as FoamLinkFill } from './icons/LinkFill';
export { Link as LinkIcon } from './icons/Link';
export { Link as FoamLink } from './icons/Link';
export { ListDuotone as ListDuotoneIcon } from './icons/ListDuotone';
export { ListDuotone as FoamListDuotone } from './icons/ListDuotone';
export { ListFill as ListFillIcon } from './icons/ListFill';
export { ListFill as FoamListFill } from './icons/ListFill';
export { ListFilterDuotone as ListFilterDuotoneIcon } from './icons/ListFilterDuotone';
export { ListFilterDuotone as FoamListFilterDuotone } from './icons/ListFilterDuotone';
export { ListFilterFill as ListFilterFillIcon } from './icons/ListFilterFill';
export { ListFilterFill as FoamListFilterFill } from './icons/ListFilterFill';
export { ListFilter as ListFilterIcon } from './icons/ListFilter';
export { ListFilter as FoamListFilter } from './icons/ListFilter';
export { ListIndentDecreaseDuotone as ListIndentDecreaseDuotoneIcon } from './icons/ListIndentDecreaseDuotone';
export { ListIndentDecreaseDuotone as FoamListIndentDecreaseDuotone } from './icons/ListIndentDecreaseDuotone';
export { ListIndentDecreaseFill as ListIndentDecreaseFillIcon } from './icons/ListIndentDecreaseFill';
export { ListIndentDecreaseFill as FoamListIndentDecreaseFill } from './icons/ListIndentDecreaseFill';
export { ListIndentDecrease as ListIndentDecreaseIcon } from './icons/ListIndentDecrease';
export { ListIndentDecrease as FoamListIndentDecrease } from './icons/ListIndentDecrease';
export { ListIndentIncreaseDuotone as ListIndentIncreaseDuotoneIcon } from './icons/ListIndentIncreaseDuotone';
export { ListIndentIncreaseDuotone as FoamListIndentIncreaseDuotone } from './icons/ListIndentIncreaseDuotone';
export { ListIndentIncreaseFill as ListIndentIncreaseFillIcon } from './icons/ListIndentIncreaseFill';
export { ListIndentIncreaseFill as FoamListIndentIncreaseFill } from './icons/ListIndentIncreaseFill';
export { ListIndentIncrease as ListIndentIncreaseIcon } from './icons/ListIndentIncrease';
export { ListIndentIncrease as FoamListIndentIncrease } from './icons/ListIndentIncrease';
export { ListOrderedDuotone as ListOrderedDuotoneIcon } from './icons/ListOrderedDuotone';
export { ListOrderedDuotone as FoamListOrderedDuotone } from './icons/ListOrderedDuotone';
export { ListOrderedFill as ListOrderedFillIcon } from './icons/ListOrderedFill';
export { ListOrderedFill as FoamListOrderedFill } from './icons/ListOrderedFill';
export { ListOrdered as ListOrderedIcon } from './icons/ListOrdered';
export { ListOrdered as FoamListOrdered } from './icons/ListOrdered';
export { List as ListIcon } from './icons/List';
export { List as FoamList } from './icons/List';
export { LoaderCircleDuotone as LoaderCircleDuotoneIcon } from './icons/LoaderCircleDuotone';
export { LoaderCircleDuotone as FoamLoaderCircleDuotone } from './icons/LoaderCircleDuotone';
export { LoaderCircleFill as LoaderCircleFillIcon } from './icons/LoaderCircleFill';
export { LoaderCircleFill as FoamLoaderCircleFill } from './icons/LoaderCircleFill';
export { LoaderCircle as LoaderCircleIcon } from './icons/LoaderCircle';
export { LoaderCircle as FoamLoaderCircle } from './icons/LoaderCircle';
export { LockDuotone as LockDuotoneIcon } from './icons/LockDuotone';
export { LockDuotone as FoamLockDuotone } from './icons/LockDuotone';
export { LockFill as LockFillIcon } from './icons/LockFill';
export { LockFill as FoamLockFill } from './icons/LockFill';
export { Lock as LockIcon } from './icons/Lock';
export { Lock as FoamLock } from './icons/Lock';
export { LogOutDuotone as LogOutDuotoneIcon } from './icons/LogOutDuotone';
export { LogOutDuotone as FoamLogOutDuotone } from './icons/LogOutDuotone';
export { LogOutFill as LogOutFillIcon } from './icons/LogOutFill';
export { LogOutFill as FoamLogOutFill } from './icons/LogOutFill';
export { LogOut as LogOutIcon } from './icons/LogOut';
export { LogOut as FoamLogOut } from './icons/LogOut';
export { MailDuotone as MailDuotoneIcon } from './icons/MailDuotone';
export { MailDuotone as FoamMailDuotone } from './icons/MailDuotone';
export { MailFill as MailFillIcon } from './icons/MailFill';
export { MailFill as FoamMailFill } from './icons/MailFill';
export { MailMoveDuotone as MailMoveDuotoneIcon } from './icons/MailMoveDuotone';
export { MailMoveDuotone as FoamMailMoveDuotone } from './icons/MailMoveDuotone';
export { MailMoveFill as MailMoveFillIcon } from './icons/MailMoveFill';
export { MailMoveFill as FoamMailMoveFill } from './icons/MailMoveFill';
export { MailMove as MailMoveIcon } from './icons/MailMove';
export { MailMove as FoamMailMove } from './icons/MailMove';
export { MailPlusDuotone as MailPlusDuotoneIcon } from './icons/MailPlusDuotone';
export { MailPlusDuotone as FoamMailPlusDuotone } from './icons/MailPlusDuotone';
export { MailPlusFill as MailPlusFillIcon } from './icons/MailPlusFill';
export { MailPlusFill as FoamMailPlusFill } from './icons/MailPlusFill';
export { MailPlus as MailPlusIcon } from './icons/MailPlus';
export { MailPlus as FoamMailPlus } from './icons/MailPlus';
export { Mail as MailIcon } from './icons/Mail';
export { Mail as FoamMail } from './icons/Mail';
export { MapPinDuotone as MapPinDuotoneIcon } from './icons/MapPinDuotone';
export { MapPinDuotone as FoamMapPinDuotone } from './icons/MapPinDuotone';
export { MapPinFill as MapPinFillIcon } from './icons/MapPinFill';
export { MapPinFill as FoamMapPinFill } from './icons/MapPinFill';
export { MapPin as MapPinIcon } from './icons/MapPin';
export { MapPin as FoamMapPin } from './icons/MapPin';
export { MaximizeDuotone as MaximizeDuotoneIcon } from './icons/MaximizeDuotone';
export { MaximizeDuotone as FoamMaximizeDuotone } from './icons/MaximizeDuotone';
export { MaximizeFill as MaximizeFillIcon } from './icons/MaximizeFill';
export { MaximizeFill as FoamMaximizeFill } from './icons/MaximizeFill';
export { Maximize as MaximizeIcon } from './icons/Maximize';
export { Maximize as FoamMaximize } from './icons/Maximize';
export { MediaKitsDuotone as MediaKitsDuotoneIcon } from './icons/MediaKitsDuotone';
export { MediaKitsDuotone as FoamMediaKitsDuotone } from './icons/MediaKitsDuotone';
export { MediaKitsFill as MediaKitsFillIcon } from './icons/MediaKitsFill';
export { MediaKitsFill as FoamMediaKitsFill } from './icons/MediaKitsFill';
export { MediaKits as MediaKitsIcon } from './icons/MediaKits';
export { MediaKits as FoamMediaKits } from './icons/MediaKits';
export { MegaphoneActiveDuotone as MegaphoneActiveDuotoneIcon } from './icons/MegaphoneActiveDuotone';
export { MegaphoneActiveDuotone as FoamMegaphoneActiveDuotone } from './icons/MegaphoneActiveDuotone';
export { MegaphoneActiveFill as MegaphoneActiveFillIcon } from './icons/MegaphoneActiveFill';
export { MegaphoneActiveFill as FoamMegaphoneActiveFill } from './icons/MegaphoneActiveFill';
export { MegaphoneActive as MegaphoneActiveIcon } from './icons/MegaphoneActive';
export { MegaphoneActive as FoamMegaphoneActive } from './icons/MegaphoneActive';
export { MegaphoneDuotone as MegaphoneDuotoneIcon } from './icons/MegaphoneDuotone';
export { MegaphoneDuotone as FoamMegaphoneDuotone } from './icons/MegaphoneDuotone';
export { MegaphoneFill as MegaphoneFillIcon } from './icons/MegaphoneFill';
export { MegaphoneFill as FoamMegaphoneFill } from './icons/MegaphoneFill';
export { Megaphone as MegaphoneIcon } from './icons/Megaphone';
export { Megaphone as FoamMegaphone } from './icons/Megaphone';
export { MenuDuotone as MenuDuotoneIcon } from './icons/MenuDuotone';
export { MenuDuotone as FoamMenuDuotone } from './icons/MenuDuotone';
export { MenuFill as MenuFillIcon } from './icons/MenuFill';
export { MenuFill as FoamMenuFill } from './icons/MenuFill';
export { Menu as MenuIcon } from './icons/Menu';
export { Menu as FoamMenu } from './icons/Menu';
export { MessageSquareDuotone as MessageSquareDuotoneIcon } from './icons/MessageSquareDuotone';
export { MessageSquareDuotone as FoamMessageSquareDuotone } from './icons/MessageSquareDuotone';
export { MessageSquareFill as MessageSquareFillIcon } from './icons/MessageSquareFill';
export { MessageSquareFill as FoamMessageSquareFill } from './icons/MessageSquareFill';
export { MessageSquare as MessageSquareIcon } from './icons/MessageSquare';
export { MessageSquare as FoamMessageSquare } from './icons/MessageSquare';
export { MessagesSquareDuotone as MessagesSquareDuotoneIcon } from './icons/MessagesSquareDuotone';
export { MessagesSquareDuotone as FoamMessagesSquareDuotone } from './icons/MessagesSquareDuotone';
export { MessagesSquareFill as MessagesSquareFillIcon } from './icons/MessagesSquareFill';
export { MessagesSquareFill as FoamMessagesSquareFill } from './icons/MessagesSquareFill';
export { MessagesSquare as MessagesSquareIcon } from './icons/MessagesSquare';
export { MessagesSquare as FoamMessagesSquare } from './icons/MessagesSquare';
export { MinusDuotone as MinusDuotoneIcon } from './icons/MinusDuotone';
export { MinusDuotone as FoamMinusDuotone } from './icons/MinusDuotone';
export { MinusFill as MinusFillIcon } from './icons/MinusFill';
export { MinusFill as FoamMinusFill } from './icons/MinusFill';
export { Minus as MinusIcon } from './icons/Minus';
export { Minus as FoamMinus } from './icons/Minus';
export { MoonDuotone as MoonDuotoneIcon } from './icons/MoonDuotone';
export { MoonDuotone as FoamMoonDuotone } from './icons/MoonDuotone';
export { MoonFill as MoonFillIcon } from './icons/MoonFill';
export { MoonFill as FoamMoonFill } from './icons/MoonFill';
export { Moon as MoonIcon } from './icons/Moon';
export { Moon as FoamMoon } from './icons/Moon';
export { MousePointerClickDuotone as MousePointerClickDuotoneIcon } from './icons/MousePointerClickDuotone';
export { MousePointerClickDuotone as FoamMousePointerClickDuotone } from './icons/MousePointerClickDuotone';
export { MousePointerClickFill as MousePointerClickFillIcon } from './icons/MousePointerClickFill';
export { MousePointerClickFill as FoamMousePointerClickFill } from './icons/MousePointerClickFill';
export { MousePointerClick as MousePointerClickIcon } from './icons/MousePointerClick';
export { MousePointerClick as FoamMousePointerClick } from './icons/MousePointerClick';
export { MoveDuotone as MoveDuotoneIcon } from './icons/MoveDuotone';
export { MoveDuotone as FoamMoveDuotone } from './icons/MoveDuotone';
export { MoveFill as MoveFillIcon } from './icons/MoveFill';
export { MoveFill as FoamMoveFill } from './icons/MoveFill';
export { Move as MoveIcon } from './icons/Move';
export { Move as FoamMove } from './icons/Move';
export { PanelLeftDuotone as PanelLeftDuotoneIcon } from './icons/PanelLeftDuotone';
export { PanelLeftDuotone as FoamPanelLeftDuotone } from './icons/PanelLeftDuotone';
export { PanelLeftFill as PanelLeftFillIcon } from './icons/PanelLeftFill';
export { PanelLeftFill as FoamPanelLeftFill } from './icons/PanelLeftFill';
export { PanelLeft as PanelLeftIcon } from './icons/PanelLeft';
export { PanelLeft as FoamPanelLeft } from './icons/PanelLeft';
export { PanelRightDuotone as PanelRightDuotoneIcon } from './icons/PanelRightDuotone';
export { PanelRightDuotone as FoamPanelRightDuotone } from './icons/PanelRightDuotone';
export { PanelRightFill as PanelRightFillIcon } from './icons/PanelRightFill';
export { PanelRightFill as FoamPanelRightFill } from './icons/PanelRightFill';
export { PanelRight as PanelRightIcon } from './icons/PanelRight';
export { PanelRight as FoamPanelRight } from './icons/PanelRight';
export { PencilDuotone as PencilDuotoneIcon } from './icons/PencilDuotone';
export { PencilDuotone as FoamPencilDuotone } from './icons/PencilDuotone';
export { PencilFill as PencilFillIcon } from './icons/PencilFill';
export { PencilFill as FoamPencilFill } from './icons/PencilFill';
export { Pencil as PencilIcon } from './icons/Pencil';
export { Pencil as FoamPencil } from './icons/Pencil';
export { PinDuotone as PinDuotoneIcon } from './icons/PinDuotone';
export { PinDuotone as FoamPinDuotone } from './icons/PinDuotone';
export { PinFill as PinFillIcon } from './icons/PinFill';
export { PinFill as FoamPinFill } from './icons/PinFill';
export { Pin as PinIcon } from './icons/Pin';
export { Pin as FoamPin } from './icons/Pin';
export { PlayDuotone as PlayDuotoneIcon } from './icons/PlayDuotone';
export { PlayDuotone as FoamPlayDuotone } from './icons/PlayDuotone';
export { PlayFill as PlayFillIcon } from './icons/PlayFill';
export { PlayFill as FoamPlayFill } from './icons/PlayFill';
export { Play as PlayIcon } from './icons/Play';
export { Play as FoamPlay } from './icons/Play';
export { PlusDuotone as PlusDuotoneIcon } from './icons/PlusDuotone';
export { PlusDuotone as FoamPlusDuotone } from './icons/PlusDuotone';
export { PlusFill as PlusFillIcon } from './icons/PlusFill';
export { PlusFill as FoamPlusFill } from './icons/PlusFill';
export { Plus as PlusIcon } from './icons/Plus';
export { Plus as FoamPlus } from './icons/Plus';
export { ReachDuotone as ReachDuotoneIcon } from './icons/ReachDuotone';
export { ReachDuotone as FoamReachDuotone } from './icons/ReachDuotone';
export { ReachFill as ReachFillIcon } from './icons/ReachFill';
export { ReachFill as FoamReachFill } from './icons/ReachFill';
export { Reach as ReachIcon } from './icons/Reach';
export { Reach as FoamReach } from './icons/Reach';
export { ReelDuotone as ReelDuotoneIcon } from './icons/ReelDuotone';
export { ReelDuotone as FoamReelDuotone } from './icons/ReelDuotone';
export { ReelFill as ReelFillIcon } from './icons/ReelFill';
export { ReelFill as FoamReelFill } from './icons/ReelFill';
export { Reel as ReelIcon } from './icons/Reel';
export { Reel as FoamReel } from './icons/Reel';
export { RefreshCwDuotone as RefreshCwDuotoneIcon } from './icons/RefreshCwDuotone';
export { RefreshCwDuotone as FoamRefreshCwDuotone } from './icons/RefreshCwDuotone';
export { RefreshCwFill as RefreshCwFillIcon } from './icons/RefreshCwFill';
export { RefreshCwFill as FoamRefreshCwFill } from './icons/RefreshCwFill';
export { RefreshCw as RefreshCwIcon } from './icons/RefreshCw';
export { RefreshCw as FoamRefreshCw } from './icons/RefreshCw';
export { RemoveFormattingDuotone as RemoveFormattingDuotoneIcon } from './icons/RemoveFormattingDuotone';
export { RemoveFormattingDuotone as FoamRemoveFormattingDuotone } from './icons/RemoveFormattingDuotone';
export { RemoveFormattingFill as RemoveFormattingFillIcon } from './icons/RemoveFormattingFill';
export { RemoveFormattingFill as FoamRemoveFormattingFill } from './icons/RemoveFormattingFill';
export { RemoveFormatting as RemoveFormattingIcon } from './icons/RemoveFormatting';
export { RemoveFormatting as FoamRemoveFormatting } from './icons/RemoveFormatting';
export { ReplyDuotone as ReplyDuotoneIcon } from './icons/ReplyDuotone';
export { ReplyDuotone as FoamReplyDuotone } from './icons/ReplyDuotone';
export { ReplyFill as ReplyFillIcon } from './icons/ReplyFill';
export { ReplyFill as FoamReplyFill } from './icons/ReplyFill';
export { Reply as ReplyIcon } from './icons/Reply';
export { Reply as FoamReply } from './icons/Reply';
export { RotateCwDuotone as RotateCwDuotoneIcon } from './icons/RotateCwDuotone';
export { RotateCwDuotone as FoamRotateCwDuotone } from './icons/RotateCwDuotone';
export { RotateCwFill as RotateCwFillIcon } from './icons/RotateCwFill';
export { RotateCwFill as FoamRotateCwFill } from './icons/RotateCwFill';
export { RotateCw as RotateCwIcon } from './icons/RotateCw';
export { RotateCw as FoamRotateCw } from './icons/RotateCw';
export { Rows2Duotone as Rows2DuotoneIcon } from './icons/Rows2Duotone';
export { Rows2Duotone as FoamRows2Duotone } from './icons/Rows2Duotone';
export { Rows2Fill as Rows2FillIcon } from './icons/Rows2Fill';
export { Rows2Fill as FoamRows2Fill } from './icons/Rows2Fill';
export { Rows2 as Rows2Icon } from './icons/Rows2';
export { Rows2 as FoamRows2 } from './icons/Rows2';
export { SaveDuotone as SaveDuotoneIcon } from './icons/SaveDuotone';
export { SaveDuotone as FoamSaveDuotone } from './icons/SaveDuotone';
export { SaveFill as SaveFillIcon } from './icons/SaveFill';
export { SaveFill as FoamSaveFill } from './icons/SaveFill';
export { Save as SaveIcon } from './icons/Save';
export { Save as FoamSave } from './icons/Save';
export { SearchDuotone as SearchDuotoneIcon } from './icons/SearchDuotone';
export { SearchDuotone as FoamSearchDuotone } from './icons/SearchDuotone';
export { SearchFill as SearchFillIcon } from './icons/SearchFill';
export { SearchFill as FoamSearchFill } from './icons/SearchFill';
export { SearchUserDuotone as SearchUserDuotoneIcon } from './icons/SearchUserDuotone';
export { SearchUserDuotone as FoamSearchUserDuotone } from './icons/SearchUserDuotone';
export { SearchUserFill as SearchUserFillIcon } from './icons/SearchUserFill';
export { SearchUserFill as FoamSearchUserFill } from './icons/SearchUserFill';
export { SearchUser as SearchUserIcon } from './icons/SearchUser';
export { SearchUser as FoamSearchUser } from './icons/SearchUser';
export { Search as SearchIcon } from './icons/Search';
export { Search as FoamSearch } from './icons/Search';
export { ShareDuotone as ShareDuotoneIcon } from './icons/ShareDuotone';
export { ShareDuotone as FoamShareDuotone } from './icons/ShareDuotone';
export { ShareFill as ShareFillIcon } from './icons/ShareFill';
export { ShareFill as FoamShareFill } from './icons/ShareFill';
export { Share as ShareIcon } from './icons/Share';
export { Share as FoamShare } from './icons/Share';
export { SlidersHorizontalDuotone as SlidersHorizontalDuotoneIcon } from './icons/SlidersHorizontalDuotone';
export { SlidersHorizontalDuotone as FoamSlidersHorizontalDuotone } from './icons/SlidersHorizontalDuotone';
export { SlidersHorizontalFill as SlidersHorizontalFillIcon } from './icons/SlidersHorizontalFill';
export { SlidersHorizontalFill as FoamSlidersHorizontalFill } from './icons/SlidersHorizontalFill';
export { SlidersHorizontal as SlidersHorizontalIcon } from './icons/SlidersHorizontal';
export { SlidersHorizontal as FoamSlidersHorizontal } from './icons/SlidersHorizontal';
export { SmileDuotone as SmileDuotoneIcon } from './icons/SmileDuotone';
export { SmileDuotone as FoamSmileDuotone } from './icons/SmileDuotone';
export { SmileFill as SmileFillIcon } from './icons/SmileFill';
export { SmileFill as FoamSmileFill } from './icons/SmileFill';
export { Smile as SmileIcon } from './icons/Smile';
export { Smile as FoamSmile } from './icons/Smile';
export { SparklesDuotone as SparklesDuotoneIcon } from './icons/SparklesDuotone';
export { SparklesDuotone as FoamSparklesDuotone } from './icons/SparklesDuotone';
export { SparklesFill as SparklesFillIcon } from './icons/SparklesFill';
export { SparklesFill as FoamSparklesFill } from './icons/SparklesFill';
export { Sparkles as SparklesIcon } from './icons/Sparkles';
export { Sparkles as FoamSparkles } from './icons/Sparkles';
export { SquareDuotone as SquareDuotoneIcon } from './icons/SquareDuotone';
export { SquareDuotone as FoamSquareDuotone } from './icons/SquareDuotone';
export { SquareFill as SquareFillIcon } from './icons/SquareFill';
export { SquareFill as FoamSquareFill } from './icons/SquareFill';
export { SquarePenDuotone as SquarePenDuotoneIcon } from './icons/SquarePenDuotone';
export { SquarePenDuotone as FoamSquarePenDuotone } from './icons/SquarePenDuotone';
export { SquarePenFill as SquarePenFillIcon } from './icons/SquarePenFill';
export { SquarePenFill as FoamSquarePenFill } from './icons/SquarePenFill';
export { SquarePen as SquarePenIcon } from './icons/SquarePen';
export { SquarePen as FoamSquarePen } from './icons/SquarePen';
export { Square as SquareIcon } from './icons/Square';
export { Square as FoamSquare } from './icons/Square';
export { StarDuotone as StarDuotoneIcon } from './icons/StarDuotone';
export { StarDuotone as FoamStarDuotone } from './icons/StarDuotone';
export { StarFill as StarFillIcon } from './icons/StarFill';
export { StarFill as FoamStarFill } from './icons/StarFill';
export { Star as StarIcon } from './icons/Star';
export { Star as FoamStar } from './icons/Star';
export { SunDuotone as SunDuotoneIcon } from './icons/SunDuotone';
export { SunDuotone as FoamSunDuotone } from './icons/SunDuotone';
export { SunFill as SunFillIcon } from './icons/SunFill';
export { SunFill as FoamSunFill } from './icons/SunFill';
export { Sun as SunIcon } from './icons/Sun';
export { Sun as FoamSun } from './icons/Sun';
export { TextAlignCenterDuotone as TextAlignCenterDuotoneIcon } from './icons/TextAlignCenterDuotone';
export { TextAlignCenterDuotone as FoamTextAlignCenterDuotone } from './icons/TextAlignCenterDuotone';
export { TextAlignCenterFill as TextAlignCenterFillIcon } from './icons/TextAlignCenterFill';
export { TextAlignCenterFill as FoamTextAlignCenterFill } from './icons/TextAlignCenterFill';
export { TextAlignCenter as TextAlignCenterIcon } from './icons/TextAlignCenter';
export { TextAlignCenter as FoamTextAlignCenter } from './icons/TextAlignCenter';
export { TextAlignEndDuotone as TextAlignEndDuotoneIcon } from './icons/TextAlignEndDuotone';
export { TextAlignEndDuotone as FoamTextAlignEndDuotone } from './icons/TextAlignEndDuotone';
export { TextAlignEndFill as TextAlignEndFillIcon } from './icons/TextAlignEndFill';
export { TextAlignEndFill as FoamTextAlignEndFill } from './icons/TextAlignEndFill';
export { TextAlignEnd as TextAlignEndIcon } from './icons/TextAlignEnd';
export { TextAlignEnd as FoamTextAlignEnd } from './icons/TextAlignEnd';
export { TextAlignJustifyDuotone as TextAlignJustifyDuotoneIcon } from './icons/TextAlignJustifyDuotone';
export { TextAlignJustifyDuotone as FoamTextAlignJustifyDuotone } from './icons/TextAlignJustifyDuotone';
export { TextAlignJustifyFill as TextAlignJustifyFillIcon } from './icons/TextAlignJustifyFill';
export { TextAlignJustifyFill as FoamTextAlignJustifyFill } from './icons/TextAlignJustifyFill';
export { TextAlignJustify as TextAlignJustifyIcon } from './icons/TextAlignJustify';
export { TextAlignJustify as FoamTextAlignJustify } from './icons/TextAlignJustify';
export { TextAlignStartDuotone as TextAlignStartDuotoneIcon } from './icons/TextAlignStartDuotone';
export { TextAlignStartDuotone as FoamTextAlignStartDuotone } from './icons/TextAlignStartDuotone';
export { TextAlignStartFill as TextAlignStartFillIcon } from './icons/TextAlignStartFill';
export { TextAlignStartFill as FoamTextAlignStartFill } from './icons/TextAlignStartFill';
export { TextAlignStart as TextAlignStartIcon } from './icons/TextAlignStart';
export { TextAlignStart as FoamTextAlignStart } from './icons/TextAlignStart';
export { ThumbsDownDuotone as ThumbsDownDuotoneIcon } from './icons/ThumbsDownDuotone';
export { ThumbsDownDuotone as FoamThumbsDownDuotone } from './icons/ThumbsDownDuotone';
export { ThumbsDownFill as ThumbsDownFillIcon } from './icons/ThumbsDownFill';
export { ThumbsDownFill as FoamThumbsDownFill } from './icons/ThumbsDownFill';
export { ThumbsDown as ThumbsDownIcon } from './icons/ThumbsDown';
export { ThumbsDown as FoamThumbsDown } from './icons/ThumbsDown';
export { ThumbsUpDuotone as ThumbsUpDuotoneIcon } from './icons/ThumbsUpDuotone';
export { ThumbsUpDuotone as FoamThumbsUpDuotone } from './icons/ThumbsUpDuotone';
export { ThumbsUpFill as ThumbsUpFillIcon } from './icons/ThumbsUpFill';
export { ThumbsUpFill as FoamThumbsUpFill } from './icons/ThumbsUpFill';
export { ThumbsUp as ThumbsUpIcon } from './icons/ThumbsUp';
export { ThumbsUp as FoamThumbsUp } from './icons/ThumbsUp';
export { TrashDuotone as TrashDuotoneIcon } from './icons/TrashDuotone';
export { TrashDuotone as FoamTrashDuotone } from './icons/TrashDuotone';
export { TrashFill as TrashFillIcon } from './icons/TrashFill';
export { TrashFill as FoamTrashFill } from './icons/TrashFill';
export { Trash as TrashIcon } from './icons/Trash';
export { Trash as FoamTrash } from './icons/Trash';
export { TrendingDownDuotone as TrendingDownDuotoneIcon } from './icons/TrendingDownDuotone';
export { TrendingDownDuotone as FoamTrendingDownDuotone } from './icons/TrendingDownDuotone';
export { TrendingDownFill as TrendingDownFillIcon } from './icons/TrendingDownFill';
export { TrendingDownFill as FoamTrendingDownFill } from './icons/TrendingDownFill';
export { TrendingDown as TrendingDownIcon } from './icons/TrendingDown';
export { TrendingDown as FoamTrendingDown } from './icons/TrendingDown';
export { TrendingUpDuotone as TrendingUpDuotoneIcon } from './icons/TrendingUpDuotone';
export { TrendingUpDuotone as FoamTrendingUpDuotone } from './icons/TrendingUpDuotone';
export { TrendingUpFill as TrendingUpFillIcon } from './icons/TrendingUpFill';
export { TrendingUpFill as FoamTrendingUpFill } from './icons/TrendingUpFill';
export { TrendingUp as TrendingUpIcon } from './icons/TrendingUp';
export { TrendingUp as FoamTrendingUp } from './icons/TrendingUp';
export { TriangleDownUpDuotone as TriangleDownUpDuotoneIcon } from './icons/TriangleDownUpDuotone';
export { TriangleDownUpDuotone as FoamTriangleDownUpDuotone } from './icons/TriangleDownUpDuotone';
export { TriangleDownUpFill as TriangleDownUpFillIcon } from './icons/TriangleDownUpFill';
export { TriangleDownUpFill as FoamTriangleDownUpFill } from './icons/TriangleDownUpFill';
export { TriangleDownUp as TriangleDownUpIcon } from './icons/TriangleDownUp';
export { TriangleDownUp as FoamTriangleDownUp } from './icons/TriangleDownUp';
export { UnlinkDuotone as UnlinkDuotoneIcon } from './icons/UnlinkDuotone';
export { UnlinkDuotone as FoamUnlinkDuotone } from './icons/UnlinkDuotone';
export { UnlinkFill as UnlinkFillIcon } from './icons/UnlinkFill';
export { UnlinkFill as FoamUnlinkFill } from './icons/UnlinkFill';
export { Unlink as UnlinkIcon } from './icons/Unlink';
export { Unlink as FoamUnlink } from './icons/Unlink';
export { UnlockDuotone as UnlockDuotoneIcon } from './icons/UnlockDuotone';
export { UnlockDuotone as FoamUnlockDuotone } from './icons/UnlockDuotone';
export { UnlockFill as UnlockFillIcon } from './icons/UnlockFill';
export { UnlockFill as FoamUnlockFill } from './icons/UnlockFill';
export { Unlock as UnlockIcon } from './icons/Unlock';
export { Unlock as FoamUnlock } from './icons/Unlock';
export { UploadDuotone as UploadDuotoneIcon } from './icons/UploadDuotone';
export { UploadDuotone as FoamUploadDuotone } from './icons/UploadDuotone';
export { UploadFill as UploadFillIcon } from './icons/UploadFill';
export { UploadFill as FoamUploadFill } from './icons/UploadFill';
export { Upload as UploadIcon } from './icons/Upload';
export { Upload as FoamUpload } from './icons/Upload';
export { UserDuotone as UserDuotoneIcon } from './icons/UserDuotone';
export { UserDuotone as FoamUserDuotone } from './icons/UserDuotone';
export { UserFill as UserFillIcon } from './icons/UserFill';
export { UserFill as FoamUserFill } from './icons/UserFill';
export { User as UserIcon } from './icons/User';
export { User as FoamUser } from './icons/User';
export { UsersDuotone as UsersDuotoneIcon } from './icons/UsersDuotone';
export { UsersDuotone as FoamUsersDuotone } from './icons/UsersDuotone';
export { UsersFill as UsersFillIcon } from './icons/UsersFill';
export { UsersFill as FoamUsersFill } from './icons/UsersFill';
export { Users as UsersIcon } from './icons/Users';
export { Users as FoamUsers } from './icons/Users';
export { Volume2Duotone as Volume2DuotoneIcon } from './icons/Volume2Duotone';
export { Volume2Duotone as FoamVolume2Duotone } from './icons/Volume2Duotone';
export { Volume2Fill as Volume2FillIcon } from './icons/Volume2Fill';
export { Volume2Fill as FoamVolume2Fill } from './icons/Volume2Fill';
export { Volume2 as Volume2Icon } from './icons/Volume2';
export { Volume2 as FoamVolume2 } from './icons/Volume2';
export { VolumeOffDuotone as VolumeOffDuotoneIcon } from './icons/VolumeOffDuotone';
export { VolumeOffDuotone as FoamVolumeOffDuotone } from './icons/VolumeOffDuotone';
export { VolumeOffFill as VolumeOffFillIcon } from './icons/VolumeOffFill';
export { VolumeOffFill as FoamVolumeOffFill } from './icons/VolumeOffFill';
export { VolumeOff as VolumeOffIcon } from './icons/VolumeOff';
export { VolumeOff as FoamVolumeOff } from './icons/VolumeOff';

// Icon names for tooling
export const iconNames = ["Alert","AlertDuotone","AlertFill","Archive","ArchiveArrowUp","ArchiveArrowUpDuotone","ArchiveArrowUpFill","ArchiveDuotone","ArchiveFill","ArrowDown","ArrowDown01","ArrowDown01Duotone","ArrowDown01Fill","ArrowDown10","ArrowDown10Duotone","ArrowDown10Fill","ArrowDownDuotone","ArrowDownFill","ArrowDownIG","ArrowDownIGDuotone","ArrowDownIGFill","ArrowDownNarrowWide","ArrowDownNarrowWideDuotone","ArrowDownNarrowWideFill","ArrowDownSC","ArrowDownSCDuotone","ArrowDownSCFill","ArrowDownTT","ArrowDownTTDuotone","ArrowDownTTFill","ArrowDownUp","ArrowDownUpDuotone","ArrowDownUpFill","ArrowDownWideNarrow","ArrowDownWideNarrowDuotone","ArrowDownWideNarrowFill","ArrowDownYT","ArrowDownYTDuotone","ArrowDownYTFill","ArrowLeft","ArrowLeftDuotone","ArrowLeftFill","ArrowRight","ArrowRightDuotone","ArrowRightFill","ArrowRightToLine","ArrowRightToLineDuotone","ArrowRightToLineFill","ArrowUp","ArrowUpAZ","ArrowUpAZDuotone","ArrowUpAZFill","ArrowUpDuotone","ArrowUpFill","ArrowUpIG","ArrowUpIGDuotone","ArrowUpIGFill","ArrowUpNarrowWide","ArrowUpNarrowWideDuotone","ArrowUpNarrowWideFill","ArrowUpSC","ArrowUpSCDuotone","ArrowUpSCFill","ArrowUpTT","ArrowUpTTDuotone","ArrowUpTTFill","ArrowUpWideNarrow","ArrowUpWideNarrowDuotone","ArrowUpWideNarrowFill","ArrowUpYT","ArrowUpYTDuotone","ArrowUpYTFill","ArrowUpZA","ArrowUpZADuotone","ArrowUpZAFill","Ban","BanDuotone","BanFill","Bell","BellDuotone","BellFill","Bold","BoldDuotone","BoldFill","Bookmark","BookmarkDuotone","BookmarkFill","Calendar","CalendarDuotone","CalendarFill","ChartColumnSquare","ChartColumnSquareDuotone","ChartColumnSquareFill","Checkbox","CheckboxDuotone","CheckboxFill","Checkmark","CheckmarkDuotone","CheckmarkFill","ChevronDown","ChevronDownDuotone","ChevronDownFill","ChevronLeft","ChevronLeftDuotone","ChevronLeftFill","ChevronRight","ChevronRightDuotone","ChevronRightFill","ChevronUp","ChevronUpDuotone","ChevronUpFill","CircleAlert","CircleAlertDuotone","CircleAlertFill","CircleDollarSign","CircleDollarSignDuotone","CircleDollarSignFill","CircleQuestionMark","CircleQuestionMarkDuotone","CircleQuestionMarkFill","CircleX","CircleXDuotone","CircleXFill","Clock","ClockArrowDown","ClockArrowDown1","ClockArrowDownDuotone","ClockArrowDownFill","ClockArrowUp","ClockArrowUp1","ClockArrowUpDuotone","ClockArrowUpFill","ClockDuotone","ClockFill","Cog","CogDuotone","CogFill","Columns3","Columns3Duotone","Columns3Fill","Command","CommandDuotone","CommandFill","ContentPlus","ContentPlusDuotone","ContentPlusFill","Copy","CopyDuotone","CopyFill","Download","DownloadDuotone","DownloadFill","Eclipse","EclipseDuotone","EclipseFill","ExternalLink","ExternalLinkDuotone","ExternalLinkFill","Eye","EyeDuotone","EyeFill","EyeOff","EyeOffDuotone","EyeOffFill","Flame","FlameDuotone","FlameFill","Frown","FrownDuotone","FrownFill","Fullscreen","FullscreenDuotone","FullscreenFill","Globe","GlobeDuotone","GlobeFill","Grid1x2","Grid1x2Duotone","Grid1x2Fill","Grid2x2","Grid2x2Duotone","Grid2x2Fill","History","HistoryDuotone","HistoryFill","Hotspot","HotspotDuotone","HotspotFill","House","HouseDuotone","HouseFill","Image","ImageDuotone","ImageFill","Images","ImagesDuotone","ImagesFill","Inbox","InboxDuotone","InboxFill","Info","InfoDuotone","InfoFill","Italic","ItalicDuotone","ItalicFill","Link","LinkDuotone","LinkFill","List","ListDuotone","ListFill","ListFilter","ListFilterDuotone","ListFilterFill","ListIndentDecrease","ListIndentDecreaseDuotone","ListIndentDecreaseFill","ListIndentIncrease","ListIndentIncreaseDuotone","ListIndentIncreaseFill","ListOrdered","ListOrderedDuotone","ListOrderedFill","LoaderCircle","LoaderCircleDuotone","LoaderCircleFill","Lock","LockDuotone","LockFill","LogOut","LogOutDuotone","LogOutFill","Mail","MailDuotone","MailFill","MailMove","MailMoveDuotone","MailMoveFill","MailPlus","MailPlusDuotone","MailPlusFill","MapPin","MapPinDuotone","MapPinFill","Maximize","MaximizeDuotone","MaximizeFill","MediaKits","MediaKitsDuotone","MediaKitsFill","Megaphone","MegaphoneActive","MegaphoneActiveDuotone","MegaphoneActiveFill","MegaphoneDuotone","MegaphoneFill","Menu","MenuDuotone","MenuFill","MessageSquare","MessageSquareDuotone","MessageSquareFill","MessagesSquare","MessagesSquareDuotone","MessagesSquareFill","Minus","MinusDuotone","MinusFill","Moon","MoonDuotone","MoonFill","MousePointerClick","MousePointerClickDuotone","MousePointerClickFill","Move","MoveDuotone","MoveFill","PanelLeft","PanelLeftDuotone","PanelLeftFill","PanelRight","PanelRightDuotone","PanelRightFill","Pencil","PencilDuotone","PencilFill","Pin","PinDuotone","PinFill","Play","PlayDuotone","PlayFill","Plus","PlusDuotone","PlusFill","Reach","ReachDuotone","ReachFill","Reel","ReelDuotone","ReelFill","RefreshCw","RefreshCwDuotone","RefreshCwFill","RemoveFormatting","RemoveFormattingDuotone","RemoveFormattingFill","Reply","ReplyDuotone","ReplyFill","RotateCw","RotateCwDuotone","RotateCwFill","Rows2","Rows2Duotone","Rows2Fill","Save","SaveDuotone","SaveFill","Search","SearchDuotone","SearchFill","SearchUser","SearchUserDuotone","SearchUserFill","Share","ShareDuotone","ShareFill","SlidersHorizontal","SlidersHorizontalDuotone","SlidersHorizontalFill","Smile","SmileDuotone","SmileFill","Sparkles","SparklesDuotone","SparklesFill","Square","SquareDuotone","SquareFill","SquarePen","SquarePenDuotone","SquarePenFill","Star","StarDuotone","StarFill","Sun","SunDuotone","SunFill","TextAlignCenter","TextAlignCenterDuotone","TextAlignCenterFill","TextAlignEnd","TextAlignEndDuotone","TextAlignEndFill","TextAlignJustify","TextAlignJustifyDuotone","TextAlignJustifyFill","TextAlignStart","TextAlignStartDuotone","TextAlignStartFill","ThumbsDown","ThumbsDownDuotone","ThumbsDownFill","ThumbsUp","ThumbsUpDuotone","ThumbsUpFill","Trash","TrashDuotone","TrashFill","TrendingDown","TrendingDownDuotone","TrendingDownFill","TrendingUp","TrendingUpDuotone","TrendingUpFill","TriangleDownUp","TriangleDownUpDuotone","TriangleDownUpFill","Unlink","UnlinkDuotone","UnlinkFill","Unlock","UnlockDuotone","UnlockFill","Upload","UploadDuotone","UploadFill","User","UserDuotone","UserFill","Users","UsersDuotone","UsersFill","Volume2","Volume2Duotone","Volume2Fill","VolumeOff","VolumeOffDuotone","VolumeOffFill"] as const;
